= ROS 2 Installation Guide
:toc:
:toc-title: Contents
:source-highlighter: highlight.js
:xrefstyle: basic

== Introduction

This guide provides instructions on how to set up a ROS 2 environment on a Raspberry Pi or Jetson Nano. It also includes instructions on how to install the necessary packages for the Follow-Me Robot project.

The project offers two different platforms for running the Follow-Me Robot, which can be partially combined.

Choose the main processing computer: +
- Raspberry Pi 4 +
- Jetson Nano +

Choose the platform for the Robot: +
- Waveshare Alphabot2 +
- Arduino Uno and Adafruit Motor Shield v2.3 +

Recommended Setup: +
- Jetson Nano + Arduino Uno & Adafruit Motor Shield v2.3 +
or +
- Raspberry Pi 4 + Waveshare Alphabot2 +

Raspberry Pi 4 with the Arduino Uno and Adafruit Motor Shield v2.3 is also possible without any problems. It is not recommended to use the Jetson Nano with the Waveshare Alphabot2 because Waveshare Alphabot2 isn't built for the Jetson Nano.

Depending on the chosen platform, follow the corresponding instructions in the guide.


== Setting up Raspberry Pi (skip if using Jetson Nano)

=== Installing Ubuntu Server 22.04.3 LTS (64-bit) on Raspberry Pi

Download and install the official Raspberry Pi Imager from (https://www.raspberrypi.com/software). +
Choose the following parameters:

* Operating System: `Other general-purpose OS/Ubuntu/Ubuntu Server 22.04.3 LTS (64-bit)`.


== Setting up Jetson Nano (skip if using Raspberry Pi)

=== Installing Jetson Nano - Ubuntu 20.04 image

Follow this guide to install the image link:https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image?tab=readme-ov-file#jetson-nano-with-ubuntu-2004-os-image[Jetson Nano with Ubuntu 20.04 OS image]


== Connecting to Your Raspberry Pi or Jetson Nano Using SSH

Connect the Raspberry Pi or Jetson Nano to Ethernet, either directly to your PC or to your local network.

Find out the IP address of your Pi or Jetson Nano by using one of the following methods:

- Using the Router Interface:
  1. Log in to your router's web interface. This typically involves entering the router's IP address into a web browser.
  2. Look for a section named "Connected Devices," "DHCP Clients," or similar. This section should list all devices connected to the network along with their assigned IP addresses.
  3. Find the entry corresponding to your Raspberry Pi.
- Using a Network Scanner App (if connected to the same network):
  1. Use a network scanner app on your smartphone, tablet, or PC.
  2. Scan the local network for connected devices, and look for the Raspberry Pi.

Open the command prompt or terminal and type the following command:

=== for Raspberry Pi:

[source,shell]
----
ssh ubuntu@<ip address of the device>
----

Enter the password when prompted (default password: ubuntu).

=== for Jetson Nano:

[source,shell]
----
ssh jetson@<ip address of the device>
----

Enter the password when prompted (default password: jetson)


== Setting up Wi-Fi

_The instructions are based on link:https://gist.github.com/ExtremeGTX/ea1d1c12dde8261b263ab2fead983dc8[this guide] and modified for our use case._

=== Install required packages

[source,shell]
----
sudo apt-get install hostapd dnsmasq
----

=== Hostapd

The purpose of Hostapd is to set WiFi as an access point.

Write a new config file for Hostapd:
[source,shell]
----
sudo vi /etc/hostapd/hostapd.conf
----

Add the following content:
[source,shell]
----
interface=wlan0
driver=nl80211
ssid=FollowMeRobot
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=ubuntu1234
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
----

Tell Hostapd to use our config file by editing `/etc/default/hostapd` and changing the line that starts with `#DAEMON_CONF` (remove `#`).

[source,shell]
----
sudo vi /etc/default/hostapd
----

It should look like this:
[source,shell]
----
DAEMON_CONF="/etc/hostapd/hostapd.conf"
----

Start Heostapd:

[source,shell]
----
sudo systemctl unmask hostapd
sudo systemctl enable hostapd
sudo systemctl start hostapd
----

=== dnsmasq

Dnsmasq acts as a DHCP Server, so when a device connects to Raspberry Pi or Jetson Nano, it can get an IP assigned to it.

Make a backup of the default config:
[source,shell]
----
sudo cp /etc/dnsmasq.conf /etc/dnsmasq.conf.org
----

Create a new config file:
[source,shell]
----
sudo vi /etc/dnsmasq.confi
----

Add the following content:
[source,shell]
----
interface=wlan0
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
----

Reload dnsmasq config:

[source,shell]
----
sudo systemctl reload dnsmasq
----

=== Solving Startup Error

On system startup, dnsmasq will not wait for the wlan0 interface to initialize and will fail with error `wlan0 not found`.

We need to tell systemd to launch it after the network gets ready, so we will modify dnsmasq service file by adding `After=` and `Wants=` under `[Unit]` section.

[source,shell]
----
sudo vi /lib/systemd/system/dnsmasq.service
----

Add the following lines under `[Unit]`:
[source,shell]
----
[Unit]
...
After=network-online.target
Wants=network-online.target
----

=== Config Static IP

Ubuntu uses cloud-init for initial setup, following file needs to be modified to set the wlan0 IP.

Modify the cloud-init file:
[source,shell]
----
sudo vi /etc/netplan/50-cloud-init.yaml
----

Add the following content to the file:

[source,shell]
----
        wlan0:
            dhcp4: false
            addresses:
            - 192.168.4.1/24
----

The final file should look like this:

[source,shell]
----
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
            match:
                macaddress: 12:34:56:78:ab:cd
            set-name: eth0
        wlan0:
            dhcp4: false
            addresses:
            - 192.168.4.1/24
----

then run the following command to apply the changes:

[source,shell]
----
sudo netplan apply
----

Finally, reboot your Raspberry Pi or Jetson Nano and check if you can connect to it via WiFi and SSH.


for troubleshooting check the  link:installation_troubleshooting.adoc[documentation]

== Setting up ROS 2

=== Installing ROS 2 Humble on the Raspberry Pi

Follow the installation guide at (https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html.) +
Alternatively, run the link:https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/src/setup/install_ros2_humble.sh[installation script].

=== Installing ROS 2 Humble on the Jetson Nano

first we need to install the corect python version since Ros2 Humble is only compatible with python 3.8.

[source,shell]
----
sudo apt install python3.8
sudo apt install python3.8-dev
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
sudo update-alternatives --config python3
----

select the python3.8 version

and the check the version with the following command

[source,shell]
----
python3 --version
----

Because the Jetson Nano image we are using runs on Ubuntu 20.04, we can follow the same installation guide as for the Raspberry Pi and we have to instal from source 

Follow the installation guide at (https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html) +

=== Creating the Workspace


To manually create the workspace, execute the following commands:
[source,shell]
----
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws/src
----
Alternatively, run the link:https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/src/setup/create_workspace.sh[installation script]. +
If you encounter issues, follow this tutorial (https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html). 

== Install Dependencies

=== Installing OpenCV and cv_bridge

Use the _vision_opencv_ repository from this GitHub repository(https://github.com/ros-perception/vision_opencv).
Install the dependencies:
[source,shell]
----
sudo apt install python3-numpy
sudo apt install libboost-python-dev
----

Clone the repository:
[source,shell]
----
cd ~/ros2_ws/src
git clone https://github.com/ros-perception/vision_opencv.git -b humble
cd ~/ros2_ws
colcon build --symlink-install
----

Install _Python3-opencv_:
[source,shell]
----
sudo apt install python3-opencv
----

=== Install Rpi.GPIO

Install the Python GPIO Library (allows access to the GPIO Pins of the Raspberry Pi):
[source,shell]
----
pip3 install RPi.GPIO
----

=== Installing the Servo Library

Install the python libraries to enable communication with the PCA9685 servo:
[source,shell]
----
sudo pip install smbus
----

=== Installing falsk

[source,shell]
----
sudo pip3 install flask
sudo pip3 install flask-socketio
sudo pip3 install flask-cors
----

== Installing Packages

=== Installing the Camera Package

Clone the camera_package repository:
[source,shell]
----
cd ~/ros2_ws/src
git clone https://github.com/cl-ire/camera_package.git NOTE: Placeholder, update the path later
cd ~/ros2_ws
colcon build
source install/setup.bash
----

=== Uploading Yolo Config Files

Create the yolo_config folder in the src folder:
[source,shell]
----
cd ~/ros2_ws/src
mkdir yolo_config
----

Download the yolo config files from link:https://drive.google.com/drive/folders/1ytJ4Y_lNqkRaDgk9USgJK58EqizraWmm?usp=sharing[google drive].

Upload the files to the yolo_config folder using WinSCP or similar tools.

If you use `ls`, you should see the files `yolov3.cfg` and `yolov3.weights` in the yolo_config folder.


=== Installing the ros2_for_waveshare_alphabot2 Package (skip if using Arduino)

This repository is a ROS II version based upon the link:https://github.com/ShaunPrice/ROS_for_Waveshare_Alphabot2[ROS for Waveshare Alphabot2 Repository] by Shaun Price.

Download and build the Repository:

[source,shell]
----
cd ~/ros2_ws/src
git clone https://github.com/cl-ire/ros2_for_waveshare_alphabot2.git
cd ~/ros2_ws
colcon build
source install/setup.bash
----

== Building the Waveshare Alphabot2 (skip if using Arduino)

Follow this tutorial (https://www.waveshare.com/wiki/AlphaBot2) to build the Waveshare Alphabot2.


== Setting up Arduino Uno and Adafruit Motor Shield v2.3 (skip if using Alphabot2)

=== Setting up the Arduino IDE

Follow this tutorial (https://funduino.de/hardware-software) to install the Arduino IDE.

=== Build the Robot

Follow this tutorial (https://learn.adafruit.com/adafruit-motor-shield-v2-for-arduino/install-headers) to build the Adafruit Motor Shield.

Connect the DC motors to Port M3 and M4 of the Adafruit Motor Shield.
Connect a 6V power source (e.g., 4 AA batteries) to the power input of the Adafruit Motor Shield.
Connect the Adafruit Motor Shield power input to the Arduino Uno via a cable with a barrel jack and open contacts.

If you want to use the Arduino independently from the Jetson Nano, follow this guide (https://funduino.de/tutorial-hc-05-und-hc-06-bluetooth) to install the Bluetooth module HC-05. This is necessary to run certain tests wirelessly.

=== Installing the Adafruit Motor Shield Library

Follow this tutorial (https://learn.adafruit.com/adafruit-motor-shield-v2-for-arduino/install-software) to install the Motor Shield V2 library.

=== Upload the Script to the Arduino

Connect the Arduino Uno to the PC via USB cable.
Open the Arduino Script in the Arduino IDE and choose the COM port the Arduino is connected to (Tools -> Port -> COMX).
Upload the Script to the Arduino (Upload).

To test the script, open the serial monitor (Tools -> Serial Monitor) and send the following commands:

[source,shell]
----
100,100,1000
----

This should move the robot forward for 1 second.

If you want to test it more extensively, you can use the Python script (https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/src/Arduino/Test/arduino.py)


== Build the Arduino Setup (skip if using Alphabot2)

=== Connecting the Jetson Nano or Raspberry Pi and Arduino

Connect the Jetson Nano or Raspberry Pi to the Arduino Uno via USB cable.

Connect the Jetson Nano (5v 4A) or Raspberry Pi (5V 2A) to a power source. 

