= ROS 2 Installation Guide
:toc:
:toc-title: Contents
:source-highlighter: highlight.js
:xrefstyle: basic

== Setting up ROS 2 on Raspberry Pi

=== Installing the Raspberry Pi Image

Download and install the official Raspberry Pi Imager from link:https://www.raspberrypi.com/software/[Raspberry Pi Software]. +
Choose the following parameters:

* Operating System: `Other general-purpose OS/Ubuntu/Ubuntu Server 22.04.3 LTS (64-bit).`

=== Connecting to Your Raspberry Pi Using SSH

Connect the Raspberry Pi to Ethernet either directly to your PC or to your local network. +

Find out the IP address of your Pi by using one of the following methods:

- Using the Router Interface:
  1. Log in to your router's web interface. This typically involves entering the router's IP address into a web browser.
  2. Look for a section named "Connected Devices," "DHCP Clients," or similar. This section should list all devices connected to the network along with their assigned IP addresses.
  3. Find the entry corresponding to your Raspberry Pi.
- Using a Network Scanner App (if connected to the same network):
  1. Use a network scanner app on your smartphone, tablet, or PC.
  2. Scan the local network for connected devices, and look for the Raspberry Pi.

Open the command prompt or terminal and type the following command:
[source,shell]
----
ssh ubuntu@<ip address of the pi>
----

Enter the password when prompted (default password: ubuntu).

=== Installing ROS 2 Humble

Follow the installation guide at link:https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html[ROS 2 Humble Installation Guide]. +
Alternatively, run the link:https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/src/setup/install_ros2_humble.sh[ installation script].

=== Creating the Workspace

If you encounter issues, follow link:https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html[this tutorial]. +
Alternatively, run the link:https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/src/setup/create_workspace.sh[installation script]. +
To manually create the workspace, execute the following commands:
[source,shell]
----
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws/src
----

== Setting Up the Camera

=== Installing the Camera Driver

Use the `ros2_v4ls_camera` from link:https://github.com/tier4/ros2_v4l2_camera/tree/galactic[this GitHub repository]. +
Follow this link:https://gaseoustortoise.notion.site/Raspberry-Pi-Camera-bc33c733eeb4417cbd5e3db027a3a429[guide] for installation instructions. +
To check if the camera is working, open a second terminal, connect to the Pi, and run:
[source,shell]
----
ros2 topic list
----

If `/image_raw` shows up, the camera is working. +
Use ctrl + c to stop the camera.

=== Installing OpenCV and cv_bridge

Use the _vision_opencv_ repository from link:https://github.com/ros-perception/vision_opencv[this GitHub repository]. +
Install the dependencies:
[source,shell]
----
sudo apt install python3-numpy
sudo apt install libboost-python-dev
----

Clone the repository:
[source,shell]
----
cd ~/ros2_ws/src
git clone https://github.com/ros-perception/vision_opencv.git -b humble
cd ~/ros2_ws
colcon build --symlink-install
----

Install _Python3-opencv_:
[source,shell]
----
sudo apt install python3-opencv
----

=== Installing the Camera Package

Clone the camera_package repository:
[source,shell]
----
cd ~/ros2_ws/src
git clone https://github.com/cl-ire/camera_package.git NOTE: Placeholder, update the path later
cd ~/ros2_ws
colcon build --symlink-install
----

== Testing the Camera

Create a directory for images:
[source,shell]
----
cd
mkdir image
----

Start the camera:
[source,shell]
----
cd
ros2 run v4l2_camera v4l2_camera_node --ros-args -p image_size:="[640,480]"
----

Open a second terminal, connect to the Pi, and run:
[source,shell]
----
ros2 topic list
----

If `/image_raw` shows up, the camera is running. +
Run the camera_package node:

[source,shell]
----
ros2 run camera_package camera_test
----

This saves an image in the previously created `image` directory. +
If you see the image, the camera is working.

== Installing Dependencies 
=== Install Rpi.GPIO
Install the Python GPIO Library (allows acces to the GPIO Pins of the Raspberry Pi):
[source,shell]
----
pip3 install RPi.GPIO
----

=== Installing the Servo Library 
Install the python libraries to enable communication with the PCA9685 servo:
[source,shell]
----
sudo pip install smbus
----

== Installing Packages
=== Installing the ros2_for_waveshare_alphabot2 Package 

This repository is a ROS II version based upon the link:https://github.com/ShaunPrice/ROS_for_Waveshare_Alphabot2[ROS for Waveshare Alphabot2 Repository] by Shaun Price.

Download and build the Repository:

[source,shell]
----
cd ~/ros2_ws/src
git clone https://github.com/cl-ire/ros2_for_waveshare_alphabot2.git
cd ~/ros2_ws
colcon build --symlink-install
source install/setup.bash
----

  
// Line 132 might change in the future
