= Projektplan: Follow-Me Fahrroboter
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Dieses Projekt stellt eine Teamarbeit mit Beginn im 3. Semester im Umfang von acht Personen im Modul Software Engineering I und im weiterführenden Modul im 4. Semester Software Engineering II dar. Modulleitung übernimmt niemand geringeres als Herr Prof. Dr.-Ing. Habil. Jürgen Anke; Auftraggeber stellt Herr Prof. Dr.-Ing. Mario Neugebauer dar und unser Projekt-Coach ist Herr Christoph Zirkelbach.

== Projektorganisation
Wir haben unser Team wie folgt strukturiert: 

=== Teammitglieder
|===
| Teammitglied | Tätigkeitsbeschreibung 
|**Taylan Özer, Wirtschaftsinformatik, s85500**| Herr Özer übernimmt die **Projektleitung** und demnach auch administrative Aufgaben. Aufgabenfeld und Tätigkeit sind dynamisch und mit den anderen Projektrollen fließend.

|**Claire Schubert, Wirtschaftsinformatik, s85609** | Frau Schubert übernimmt zu Ihrer Tätigkeit als **stellvertretende Projektleitung** ebenfalls die Rolle als **Creative Lead** und **Architect**. Sie teilt des Weiteren Aufgaben den anderen Teammitgliedern zu und dient als Ansprechperson im technischen Zusammenhang mit dem Fahrroboter. 

|**Theresa Stasch, Wirtschaftsingenieurwesen**| Frau Stasch übernimmt zunächst die Aufgabe zur Pflegung des Beleges und im allgemeinen zur Weiterführung der Dokumentation. 

|**Johann Marthaus, Wirtschaftsinformatik, s85567**| Herr Marthaus übernimmt die Rolle als **Lead Developer** und organisiert sich mit **Jonathan Palermo**, **Danny Miersch** und zum Aufbau der Bilderkennung für den Fahrroboter.

|**Jonathan Palermo, Wirtschaftsinformatik, s85287** | Herr Palermo trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei und insbesondere in der Bilderkennung.

|**Danny Miersch, Wirtschaftsinformatik, s85567** | Herr Miersch trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei. Herr Miersch übernimmt so auch, weitere Nebentätigkeiten, wie mit unter die Kontrolle des Glossars.

|**Jeremy Ziegert, Wirtschaftsinformatik, s85299** | Herr Ziegert trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei.

| **Luca Kurth, Verwaltungsinformatik, s85459** | Herr Kurth trägt die Rolle des **Entwicklers** und trägt mit zur Entwicklung des Fahrroboters bei.
|===


=== Teamstruktur

|===
|Team |Teambeschreibung |Teammitglieder
|**Entwicklungs Team I**
|Entwicklungsteam I unter Leitung von Herr Marthaus ist zu Beginn der 1. Iteration (06.11.2023 - 19.11.2023) für die Bilderkennung des Fahrroboters zuständig.
|Johann Marthaus (Gruppenleitung), Luca Kurth, Jonathan Palermo, Jeremy Ziegert

|**Entwicklungs Team II**
|Entwicklungsteam II stellt die Recherche und die Dokumentation zum Roboter Betriebssystem II (ROS II) sicher und überwacht demnach die Schritte zur Implementierung des Betriebssystems.
|Claire Schubert, Danny Miersch
|===


== Praktiken und Bewertung
Aufgrund dessen das wir eine für uns neue Technologie ausgehändigt bekommen haben (Alphabot 2 Raspberry Pi), entschieden wir uns für einen iterativen Entwicklungsansatz. Dies half uns auf die Funktionalität des Alphabot 2 vollständig zugreifen und verstehen zu können. Dies half uns ebenfalls, unser Bilderkennungsverfahren Schritt für Schritt verbessern zu können. Folglich ist unsere Hauptpriorität zu erst ein teilweise funktionierendes System zu liefern und dies inkrementell zu verbessern und zu erweitern.

//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).


== Meilensteine und Ziele

//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone
| Target velocity

| I1
|
* Analyse der Aufgabenstellung
* Teambildung
* Erfassen der Teamkompetenzen
| 06.11.2023 - 19.11.2023
| 10

| I2
|
* Systemverständnis für Raspberry Pi und Alphabot 2 erlangen
* Verständnis für Open CV
* Entscheidung, ob ROS II verwendet werden soll
| 20.11.2023 - 03.12.2023
| 15
|===


== Deployment
Download der Software erfolgte über git clone, ebenso mit der Hilfe von zwei Repositorys auf GitHub.
//Outline the strategy for deploying the software (and its updates) into the production environment.


== Erkenntnisse (Lessons learned)
Aus unserer Sicht als Gruppe des Follow-Me-Fahrroboter-Projekts wurden während der Laufzeit der Module Software Engineering I/II viele neue Kenntnisse und auch Fähigkeiten erworben, welche mit Sicherheit auch im späteren beruflichen Umfeld von Relevanz sind.
Besonders wichtig war für uns die Erkenntnis über die Bedeutung einer strukturierten Herangehensweise in Softwareprojekten. Methoden wie OpenUP haben uns gezeigt, dass Projekte von der Planung bis hin zur Auslieferung an den Auftraggeber strukturiert und gut organisiert sein sollten, was in der Regel auch zu einem tieferen Problemverständnis führt. Die direkte Anwendbarkeit des theoretisch Erlernten aus den Vorlesungen von Herr Prof. Anke in diesem praktischen Projekt, war ebenfalls besonders wertvoll für uns als Gruppe. Ebenso wurde klar für uns, dass für eine erfolgreiche Teamarbeit eine nahtlose Kommunikation von großer Bedeutung ist und wir so auch wesentlichst zur Problemlösung für unser gegebenes Problem beitragen können. Des Weiteren wurde die Bedeutung von Testing und einer Risikoanalyse ebenfalls deutlich. Unerwartete Probleme am Raspberry Pi haben die Wichtigkeit gründlicher Tests und einer umfassenden Risikoanalyse betont. Ebenfalls war die kritische Eigen- und Gruppenreflexion immer wieder notwendig, um gruppeninterne Probleme angehen zu können. Im Allgemeinen haben wir auch durch unsere Teamarbeit nicht nur unsere technischen Fähigkeiten im Hinblick auf gegebene Hardware, GitHub und Git verbessern können, sondern auch wichtige Soft Skills erlernt, wie den Umgang mit weniger leistungsstarken Teammitgliedern und wie wir diese unterstützen können, ihre Aufgaben dennoch zeitnah mit Erfolg erledigen zu können. Die Zusammenarbeit als Team hat gezeigt, dass ein gut organisiertes und strukturiertes Team maßgeblich auch zum Projekterfolg beitragen kann. Und zusammenfassend als Gruppe können wir hier nun sagen, dass wir als Gruppe stolz darauf sind so weit gekommen zu sein, neue Fähigkeiten erlernt zu haben und unser Projekt nun Final in die Abschlussphase gebracht zu haben.


//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.
