= Dokumentation: Follow-Me-Fahrroboter
 Modulleiter: Herr Prof. Dr. -Ing. Habil. Jürgen Anke; Auftraggeber: Herr. Prof. Dr. -Ing. Mario Neugebauer; Projekt-Coach: Herr Christoph Zirkelbach;
{localdatetime}
include::../../_includes/default-attributes.inc.adoc[]

== Allgemein
Dieses Projekt stellt eine Teamarbeit mit Beginn im 3. Semester im Umfang von acht Personen im Modul Software Engineering I und im weiterführenden Modul im 4. Semester Software Engineering II dar. Modulleitung übernimmt niemand geringeres als Herr Prof. Dr.-Ing. Habil. Jürgen Anke; Auftraggeber stellt Herr Prof. Dr.-Ing. Mario Neugebauer dar und unser Projekt-Coach ist Herr Christoph Zirkelbach. 

=== Auftraggeber
Für unser gegebenes Projekt "Follow-Me Fahrroboter" stellt sich Herr Prof. Dr. -Ing. Mario Neugebauer als Auftraggeber bzw. als Product Owner und dient demnach als Hauptansprechpartner.

=== Rollenverteilung
Die Aufgaben wurden hauptsächlich nach Interessen- und Expertisengebieten verteilt und sollen im allgemeinen zum Anreiz dienen gestellte bzw. übernommene Aufgaben auch vollständig und nach bestem Wissen und Gewissen abzuschließen. 

=== Ablauf der Kommunikation unter Verwendung von Tools
Wir haben uns als Team darauf verständigt unsere interne Kommunikation in dem von unserem Projektleiter Herr Özer erstellten WhatsApp-Gruppe abzuhalten und diesen auch zum allgemeinen Austausch bei Fragen, Problem und Lösungen zu nutzen. Discord dient hier im gleichen Rahmen. In GitHub überwachen wir unsere gegenseitig gestellten Aufgaben und kontrollieren Projektstruktur. 

=== Teammitglieder
include::{includesdir}/teammitglieder.adoc[]

== Gruppenmeeting 14.03.2024 (6. Iteration)
BITTE HIER INCLUDE


=== Teamstruktur zur 6. Iteration (11.03.2024 - 25.03.2024)

|===
|Team |Teambeschreibung |Teammitglieder
|**Entwicklungs Team I**
|Entwicklungsteam I unter Leitung von Herr Marthaus ist zu Beginn der 1. Iteration (06.11.2023 - 19.11.2023) für die Bilderkennung des Fahrroboters zuständig.
|Johann Marthaus (Gruppenleitung), Jonathan Palermo, Frau Schubert
|===

Die Teammitglieder, welche nicht Teil des genanten Entwicklungsteams I und II sind, führen Ihre oben beschriebenen Aufgaben autonom weiterhin fort.

 - Unsere Teamstruktur blieb analog zur 1. Iteration unverändert und so führen wir diese Teamstruktur zunächst auch in der 2. Iteration fort.

== Iterationen
=== 6. Iteration 11.03.2024 - 25.03.2024 
=== Allgemein
==== Standerfassung aus 5. Iteration

Mit Beginn unserer 5. Iteration (04.01.2024 - 18.01.2024) hatten wir aufgrund der Weihnachtstage und den Neujahrstagen nichts weiter zunächst an Aufgaben erledigen können, dennoch ist die Zielstellung weiterhin die Vervollständigung unserer Belegarbeit. Weiterhin fehlen folgende Dokumente: Risk List, NFAs (Systemwide Requirements), Funktionale Anforderungen, Architecture Notebook und der Iteration Plan mt zwei eingebundenen Diagrammen aus dem Essence Navigator - die Issues werden hierzu noch auf GitHub formuliert.

==== Probleme und weitere Belange

- **Erster Punkt:**  


==== Ausblick

Der Ausblick für unser Projekt richtet sich überwiegend an die von uns definierten Qualitätskriterien für den Fahrroboter und die Überarbeitung der Bildkerkennung. Des Weiteren ist die zielgerichtete Optimierung des Beleges auch von großer Bedeutung und so werden die o. g. Punkte aus dem Coach-Meeting mit Herr Zirkelbach auch umgesetzt werden. 
