= Dokumentation: Follow-Me-Fahrroboter
 Modulleiter: Herr Prof. Dr. -Ing. Habil. Jürgen Anke; Auftraggeber: Herr. Prof. Dr. -Ing. Mario Neugebauer; Projekt-Coach: Herr Christoph Zirkelbach;
{localdatetime}
include::../../_includes/default-attributes.inc.adoc[]

== Allgemein
Dieses Projekt stellt eine Teamarbeit mit Beginn im 3. Semester im Umfang von acht Personen im Modul Software Engineering I und im weiterführenden Modul im 4. Semester Software Engineering II dar. Modulleitung übernimmt niemand geringeres als Herr Prof. Dr.-Ing. Habil. Jürgen Anke; Auftraggeber stellt Herr Prof. Dr.-Ing. Mario Neugebauer dar und unser Projekt-Coach ist Herr Christoph Zirkelbach. 

=== Fristen
**Abgabe Belegarbeit: 26.01.2024**

=== Auftraggeber
Für unser gegebenes Projekt "Follow-Me Fahrroboter" stellt sich Herr Prof. Dr. -Ing. Mario Neugebauer als Auftraggeber bzw. als Product Owner und dient demnach als Hauptansprechpartner.

=== Rollenverteilung
Die Aufgaben wurden hauptsächlich nach Interessen- und Expertisengebieten verteilt und sollen im allgemeinen zum Anreiz dienen gestellte bzw. übernommene Aufgaben auch vollständig und nach bestem Wissen und Gewissen abzuschließen. 

=== Ablauf der Kommunikation unter Verwendung von Tools
Wir haben uns als Team darauf verständigt unsere interne Kommunikation in dem von unserem Projektleiter Herr Özer erstellten WhatsApp-Gruppe abzuhalten und diesen auch zum allgemeinen Austausch bei Fragen, Problem und Lösungen zu nutzen. Discord dient hier im gleichen Rahmen. In GitHub überwachen wir unsere gegenseitig gestellten Aufgaben und kontrollieren Projektstruktur. 

=== Teammitglieder
include::{includesdir}/teammitglieder.adoc[]

=== Gruppenmeeting 12.12.2023 (3. Iteration)
BITTE HIER INCLUDE

=== Gruppenmeeting 14.12.2023 (3. Iteration)
BITTE HIER INCLUDE

=== Gruppenmeeting 15.12.2023 (3. Iteration)
BITTE HIER INCLUDE

=== Teamstruktur zur 3. Iteration (05.12.2023 - 19.12.2023)

|===
|Team |Teambeschreibung |Teammitglieder
|**Entwicklungs Team I**
|Entwicklungsteam I unter Leitung von Herr Marthaus ist zu Beginn der 1. Iteration (06.11.2023 - 19.11.2023) für die Bilderkennung des Fahrroboters zuständig.
|Johann Marthaus (Gruppenleitung), Luca Kurth, Jonathan Palermo, Jeremy Ziegert

|**Entwicklungs Team II**
|Entwicklungsteam II stellt die Recherche und die Dokumentation zum Roboter Betriebssystem II (ROS II) sicher und überwacht demnach die Schritte zur Implementierung des Betriebssystems.
|Claire Schubert, Danny Miersch
|===

Die Teammitglieder, welche nicht Teil des genanten Entwicklungsteams I und II sind, führen Ihre oben beschriebenen Aufgaben autonom weiterhin fort.

 - Unsere Teamstruktur blieb analog zur 1. Iteration unverändert und so führen wir diese Teamstruktur zunächst auch in der 2. Iteration fort.

== Iterationen
//tag::Iter3[]

=== *3. Iteration 05.12.2023 - 19.12.2023* 
=== Allgemein
==== Standerfassung aus 2. Iteration

Mit Beginn unserer 3. Iteration mit dem Zeitraum vom 04.12.2023 - 19.12.2023 hielten wir zeitnah am 05.12.2023 (Dienstag) ein Gruppenmeeting zur Erfassung des aktuellen Projektstandes und für das weitere Vorgehen ab. Bei diesem Meeting war ebenfalls Herr Zirkelbach als Projekt-Coach anwesend. 

 - **Erster Punkt:** Unsere Gruppe hatte einige Fragen zur Dokumentation der Architektur. Herr Zirkelbach teilte uns mit, dass in der Dokumentation nur grobe Informationen enthalten sein müssen. Beispielsweise enthält das Notebook Informationen darüber, worum es geht und welche Technik verwendet wird. Hierbei sollten ebenfalls alle Entscheidungen mit ihren dazugehörigen Begründungen und Erkenntnissen berücksichtigt werden. 

 - **Zweiter Punkt:** Ebensfalls kamen Fragen bezüglich des Essence Navigator auf. Hierbei stellte sich heraus, dass der Essence Navigator uns dabei im Rahmen des Lehrprojektes unterstützen soll, herauszufinden in welchem Projektstand wir uns befinden. Grundlegend kann man davon ausgehen, dass es von Vorteil ist, in jeder Interation auf den Essence Navigator zurückzugreifen. Jedoch wurde durch Herr Zirkelbach mitgeteilt, dass die entstandenen Diagramme vom Essence Navigator lediglich in den Iteration Plan für zwei vollständige Iterationen eingebunden und abgebildet werden sollen.

 - **Dritter Punkt:** Unsere letzte Frage betraf das Development. Den Design-Teil priorisieren wir eher in Software Engineering II - es können jedoch bereits erste Grundgedanken hinzugefügt werden. Des Weiteren können schon erste Entwürfe erstellt werden, für die Kommunikation mit der Hardware. So soll auch das OS ROS II so erklärt werden, dass sogar ein dritter nur anhand dieser nicht all zu komplexen Orientierung sich in die Gruppe mit einfinden könnte.  

 - **Vierter Punkt:** Zuletzt wurden noch grundsätzliche Ziele besprochen. Herr Zirkelbach wird noch einmal im Januar (zur letzten Iteration) mit eingebunden werden. Ebenfalls ist es wichtig die USE-CASEs richtig zu definieren und dementsprechend ein USE-CASE-Diagramm zu erstellen. Ein Beispiel hierfür ist das Starten des Fahrroboters -> das System wird hochgefahren und der Roboter fährt einer Person hinterher. Abschließend muss noch geklärt werden: Ob der Roboter, wenn sich die Person umdreht, ihr folgen soll oder ob er rückwärtsfährt, wenn eine Person sich auf ihn hinzu bewegt.

==== Probleme und weitere Belange
- **Erster Punkt:** Es wurde bereits ein USE-CASES-Diagramm von Herr Kurth erstellt, jedoch wurde dieses vor dem Treffen mit dem Projekt-Coach am 05.12.2023 (Dienstag) nicht auf GitHub gepushed. Dieses Diagramm konnte dementsprechend auch nicht Herr Zirkelbach gezeigt werden - nachträglich wurde das Diagramm an Herr Zirkelbach per Email gesendet. 

- **Zweiter Punkt:** Bis zum Sonntag den 10.12.2023 sollte der erste Prototyp funktionieren. Hierbei sollte der Roboter in einem leeren Raum es schaffen einer Person zu folgen. 

- **Dritter Punkt:** Wir berieten uns im allgemeinen darüber, ob wir Herr Zirkelbach zeitnah über unsere Ordnerstruktur ansprechen sollten, zwecks der Einführung einer ReadMe-Datei und eines Installation-Guides (Deutsch/Englisch).

- **Vierter Punkt:** Ein Prototyp ist noch nicht vollständig vorhanden -> Software-Komponente fehlt (Herr Marthaus)

- **Fünfter Punkt:** Der Alphabot II lässt sich über seine Kamera und einzelnen Glieder ansprechen.


==== Ausblick
Unser Ausblick bis zum Ende der 3. Iteration und mit Beginn der 4. Iteration als Team ist die Konstruktion eines 1. vollständigen Prototypen. Des Weiteren streben wir ebenfalls eine Vervollständigung der Unterlagen für unseren Beleg an.
//end::Iter3[]