= Dokumentation: Follow-Me-Fahrroboter
 Modulleiter: Herr Prof. Dr. -Ing. Habil. Jürgen Anke; Auftraggeber: Herr. Prof. Dr. -Ing. Mario Neugebauer; Projekt-Coach: Herr Christoph Zirkelbach;
{localdatetime}
include::../../_includes/default-attributes.inc.adoc[]

== Allgemein
Dieses Projekt stellt eine Teamarbeit mit Beginn im 3. Semester im Umfang von acht Personen im Modul Software Engineering I und im weiterführenden Modul im 4. Semester Software Engineering II dar. Modulleitung übernimmt niemand geringeres als Herr Prof. Dr.-Ing. Habil. Jürgen Anke; Auftraggeber stellt Herr Prof. Dr.-Ing. Mario Neugebauer dar und unser Projekt-Coach ist Herr Christoph Zirkelbach. 

=== Fristen
**Abgabe Belegarbeit: 26.01.2024**

=== Auftraggeber
Für unser gegebenes Projekt "Follow-Me Fahrroboter" stellt sich Herr Prof. Dr. -Ing. Mario Neugebauer als Auftraggeber bzw. als Product Owner und dient demnach als Hauptansprechpartner.

=== Rollenverteilung
Die Aufgaben wurden hauptsächlich nach Interessen- und Expertisengebieten verteilt und sollen im allgemeinen zum Anreiz dienen gestellte bzw. übernommene Aufgaben auch vollständig und nach bestem Wissen und Gewissen abzuschließen. 

=== Ablauf der Kommunikation unter Verwendung von Tools
Wir haben uns als Team darauf verständigt unsere interne Kommunikation in dem von unserem Projektleiter Herr Özer erstellten WhatsApp-Gruppe abzuhalten und diesen auch zum allgemeinen Austausch bei Fragen, Problem und Lösungen zu nutzen. Discord dient hier im gleichen Rahmen. In GitHub überwachen wir unsere gegenseitig gestellten Aufgaben und kontrollieren Projektstruktur. 

=== Teammitglieder
include::{includesdir}/teammitglieder.adoc[]

=== Konsultation 05.01.2024 (5. Iteration)
BITTE HIER INCLUDE


=== Teamstruktur zur 4. Iteration (20.12.2023 - 03.01.2024)

|===
|Team |Teambeschreibung |Teammitglieder
|**Entwicklungs Team I**
|Entwicklungsteam I unter Leitung von Herr Marthaus ist zu Beginn der 1. Iteration (06.11.2023 - 19.11.2023) für die Bilderkennung des Fahrroboters zuständig.
|Johann Marthaus (Gruppenleitung), Luca Kurth, Jonathan Palermo, Jeremy Ziegert

|**Entwicklungs Team II**
|Entwicklungsteam II stellt die Recherche und die Dokumentation zum Roboter Betriebssystem II (ROS II) sicher und überwacht demnach die Schritte zur Implementierung des Betriebssystems.
|Claire Schubert, Danny Miersch
|===

Die Teammitglieder, welche nicht Teil des genanten Entwicklungsteams I und II sind, führen Ihre oben beschriebenen Aufgaben autonom weiterhin fort.

 - Unsere Teamstruktur blieb analog zur 1. Iteration unverändert und so führen wir diese Teamstruktur zunächst auch in der 2. Iteration fort.

== Iterationen
//tag::Iter5[]
=== *5. Iteration 04.01.2024 - 18.01.2024* 
=== Allgemein
==== Standerfassung aus 4. Iteration

Mit Beginn unserer 5. Iteration (04.01.2024 - 18.01.2024) hatten wir aufgrund der Weihnachtstage und den Neujahrstagen nichts weiter zunächst an Aufgaben erledigen können, dennoch ist die Zielstellung weiterhin die Vervollständigung unserer Belegarbeit. Weiterhin fehlen folgende Dokumente: Risk List, NFAs (Systemwide Requirements), Funktionale Anforderungen, Architecture Notebook und der Iteration Plan mt zwei eingebundenen Diagrammen aus dem Essence Navigator - die Issues werden hierzu noch auf GitHub formuliert.

==== Probleme und weitere Belange

- **Erster Punkt:** Zur finalen Vervollständigung der Belegarbeit sind wie o. g. noch Unterlagen einzureichen bzw. in das Repository auf GitHub zu pushen. 


==== Zielstellung zur 5. Iteration
Unsere **Zielstellung für die 5. Iteration** vom Zeitraum 04.01.2024 - 18.01.2024 haben wir folgende Punkte in unser Augenmerk genommen:

- 1. Vervollständigung unserer Belegarbeit: Risk List, NFAs (Systemwide Requirements), Funktionale Anforderungen, Architecture Notebook und der Iteration Plan mt zwei eingebundenen Diagrammen aus dem Essence Navigator

- 2. Präsentation unseres Projektes in den üblichen Vorlesungs - bzw. Praktikumszeiten 


==== Ausblick
Unser Ausblick bis zum Ende der 4. Iteration und mit Beginn der 5. Iteration als Team ist die Vervollständigung unserer Belegarbeit mit den dafür vorgesehenen Dokumenten.
<<<<<<< HEAD


=======
//end::Iter5[]
>>>>>>> acc41ad5e114c258a68221a4e680cb6be9c75170
