= Dokumentation: Follow-Me-Fahrroboter
 Modulleiter: Herr Prof. Dr. -Ing. Habil. Jürgen Anke; Auftraggeber: Herr. Prof. Dr. -Ing. Mario Neugebauer; Projekt-Coach: Herr Christoph Zirkelbach;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]

== Allgemein
Dieses Projekt stellt eine Teamarbeit mit Beginn im 3. Semester im Umfang von acht Personen im Modul Software Engineering I und im weiterführenden Modul im 4. Semester Software Engineering II dar. Modulleitung übernimmt niemand geringeres als Herr Prof. Dr.-Ing. Habil. Jürgen Anke; Auftraggeber stellt Herr Prof. Dr.-Ing. Mario Neugebauer dar und unser Projekt-Coach ist Herr Christoph Zirkelbach. 

=== Fristen
**Abgabe Belegarbeit: 26.01.2024**

=== Auftraggeber
Für unser gegebenes Projekt "Follow-Me Fahrroboter" stellt sich Herr Prof. Dr. -Ing. Mario Neugebauer als Auftraggeber bzw. als Product Owner und dient demnach als Hauptansprechpartner.

=== Rollenverteilung
Die Aufgaben wurden hauptsächlich nach Interessen- und Expertisengebieten verteilt und sollen im allgemeinen zum Anreiz dienen gestellte bzw. übernommene Aufgaben auch vollständig und nach bestem Wissen und Gewissen abzuschließen. [WIRD NOCH ERGÄNZT]

=== Ablauf der Kommunikation unter Verwendung von Tools
Wir haben uns als Team darauf verständigt unsere interne Kommunikation in dem von unserem Projektleiter Herr Özer erstellten WhatsApp-Gruppe abzuhalten und diesen auch zum allgemeinen Austausch bei Fragen, Problem und Lösungen zu nutzen. Discord dient hier im gleichen Rahmen. In GitHub überwachen wir unsere gegenseitig gestellten Aufgaben und kontrollieren Projektstruktur. 

=== Teammitglieder
|===
| Teammitglied | Tätigkeitsbeschreibung 
|**Taylan Özer, Wirtschaftsinformatik, s85500**| Herr Özer übernimmt die **Projektleitung** und demnach auch administrative Aufgaben. Aufgabenfeld und Tätigkeit sind dynamisch und mit den anderen Projektrollen fließend.

|**Claire Schubert, Wirtschaftsinformatik** | Frau Schubert übernimmt zu Ihrer Tätigkeit als **stellvertretende Projektleitung** ebenfalls die Rolle als **Creative Lead** und **Architect**. Sie teilt des Weiteren Aufgaben den anderen Teammitgliedern zu und dient als Ansprechperson im technischen Zusammenhang mit dem Fahrroboter. 

|**Theresa Stasch, Wirtschaftsingenieurwesen**| Frau Stasch übernimmt zunächst die Aufgabe zur Pflegung des Beleges und im allgemeinen zur Weiterführung der Dokumentation.[NOCH UNVOLLSTÄNDIG] 

|**Johann Marthaus, Wirtschaftsinformatik**| Herr Marthaus übernimmt die Rolle als **Lead Developer** und organisiert sich mit **Jonathan Palermo**, **Danny Miersch** und [NAMEN ERGÄNZEN] zum Aufbau der Bilderkennung für den Fahrroboter.

|**Jonathan Palermo, Wirtschaftsinformatik** | Herr Palermo trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei und insbesondere in der Bilderkennung.

|**Danny Miersch, Wirtschaftsinformatik** | Herr Miersch trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei. Herr Miersch übernimmt so auch, weitere Nebentätigkeiten, wie mit unter die Kontrolle des Glossars.

|**Jeremy Ziegert, Wirtschaftsinformatik** | Herr Ziegert trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei.

| **Luca Kurth, Verwaltungsinformatik, s85459** | Herr Kurth trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei.
|===


**ALLE TÄTIGKEITEN WERDE NOCH GENAUER UND BESSER BESCHRIEBEN ES KANN NICHT ALSO NOCH WANDLEN - Taylan**


=== Teamstruktur zur 3. Iteration (05.12.2023 - 19.12.2023)

|===
|Team |Teambeschreibung |Teammitglieder
|**Entwicklungs Team I**
|Entwicklungsteam I unter Leitung von Herr Marthaus ist zu Beginn der 1. Iteration (06.11.2023 - 19.11.2023) für die Bilderkennung des Fahrroboters zuständig.
|Johann Marthaus (Gruppenleitung), Luca Kurth, Jonathan Palermo, Jeremy Ziegert

|**Entwicklungs Team II**
|Entwicklungsteam II stellt die Recherche und die Dokumentation zum Roboter Betriebssystem II (ROS II) sicher und überwacht demnach die Schritte zur Implementierung des Betriebssystems.
|Claire Schubert, Danny Miersch
|===

Die Teammitglieder, welche nicht Teil des genanten Entwicklungsteams I und II sind, führen Ihre oben beschriebenen Aufgaben autonom weiterhin fort.

 - Unsere Teamstruktur blieb analog zur 1. Iteration unverändert und so führen wir diese Teamstruktur zunächst auch in der 2. Iteration fort.

== Iterationen
=== 3. Iteration 05.12.2023 - 19.12.2023 
=== Allgemein
==== Standerfassung aus 1. Iteration

Mit Beginn unserer 3. Iteration mit dem Zeitraum vom 05.12.2023 - 19.12.2023 hielten wir zeitnah am 05.12.2023 (Dienstag) ein Gruppenmeeting zur Erfassung des aktuellen Standes des Projektes und das weitere Vorgehen. Bei diesem Meeting  war ebenfalls Herr Zirkelbach anwesend. 

 - **Erster Punkt:** Unsere Gruppe hatte einige Fragen zur Dokumentation der Architektur. Herr Zirkelbach teilte uns mit, dass in der Dokumentation nur grobe Informationen enthalten sein müssen. Bspw. enthält das Notebook Informationen darüber, worum es geht und welche Technik verwendet wird. Hierbei sollten ebensfalls alle Entscheidungen mit ihren dazugehörigen Begründungen und Erkenntnissen berücksichtigt werden. 
 - **Zweiter Punkt:** Ebensfalls kamen Fragen bezüglich des Essence Navigator auf. Hierbei stellte sich heraus, dass der Essance Navigator uns dabei unterstützt herauszufinden wo das Projekt steht. Es ist hierbei von Vorteil in jeder Interation darauf zurückzugreifen, die Grafik zu screesnshoten und diesen dann in die Dokumentation einzufügen. 
 - **Dritter Punkt:** Unsere letzte Frage betraf das Development. Der Design Teil ist eher im 2. Semester des Projektes priorisiert. Es können jedoch bereits erste Grundgedanken hinzugefügt werden. Es können grobe Entwurfspakete erstellt werden für die Kommunikation mit der Hardware. Dieser Teil kann im 2. Semester mithilfe des Quellcode präziser generiert werden. Auch das System ROS 2 sollte erklärt werden, jedoch nicht zu komplex, sodass auch unwissende das Thema verstehen. 
 - **Vierter Punkt:** Zuletzt wurden noch grundsätzliche Ziele besprochen. Herr Zirkelbach sollte noch einmal im Januar (der letzten Iteration) eingebunden werden. Ebenfalls ist es wichtig die Use Cases richtig zu definieren und einem Diagramm darzustellen.Ein Beispiel hierfür ist das Starten des Roboter, das System wird hochgefahren und der Roboter fährt einer Person hinterher. Es muss noch geklärt werden, ob der Roboter, wenn sich die Person umdreht, ihr folgen soll oder ob er rückwärtsfährt. Nebenbei sollte dokumentiert werden welche zusätzlichen Änderungen vorgenommen wurden.

==== Probleme und weitere Belange
- **Erster Punkt:** Es wurde bereits ein Diagramm der Use Cases erstellt, jedoch wurde dieses vor dem Treffen nicht auf Git Hub gepusht, weshalb dieses Diagramm nicht Herr Zirkeltbach gezeigt werden konnte. Das Diagramm wurde nachträglich per Email übermittelt. 

- **Zweiter Punkt:** Bis zum Sonntag den 10.12.2023 sollte der erste Prototyp funktionieren. Hierbei sollte der Roboter in einem leeren Raum es schaffen einer Person u folgen. 

- **Dritter Punkt:** Wir berieten uns im allgemeinen darüber, ob wir Herr Zirkelbach zeitnah über unsere Ordnerstruktur ansprechen sollten, zwecks der Einführung einer ReadMe-Datei und eines Installation-Guides (Deutsch/Englisch).

- **Vierter Punkt:** Unsere Codeformatierungsguidlines haben wir auf pep8 in Python festgelegt.

- **Fünfter Punkt:** Herr Marthaus hat es sich zur Aufgabe gemacht in unserem Team Sorge dafür zu tragen, dass wir eine ordentliche Programmierumgebung eingerichtet haben. 
 - Wir entschieden uns überwiegend für Microsoft Visual Studio Code und u. a. PyCharm, sofern der Wunsch ist hiermit arbeiten zu wollen.

=== Gruppenmeeting am 28.11.2023
==== Anlass 
Der Anlass für dieses außerplanmäßge Gruppenmeeting war, dass sich auf Geheiß von einigen Gruppenmitgliedern im Entwicklerteam II Unmut wegen Ihrer jetzigen Tätigkeiten anberaumt hat.

**Anwesenheitsliste:**

- Herr Özer (Projektleiter),
- Herr Marthaus (Leiter Entwicklungsteam II),
- Herr Ziegert (Entwickler),
- Herr Kurth (Entwickler)

**Verlauf:**

- Klärung der Motivation und arbeitsmäßgen Standerfassung von Herr Ziegert und Herr Kurth
- Herr Ziegert und Herr Kurth einverstanden mit der Umgestaltung ihrer Tätigkeiten, von Programmierung weg bzw. allgemeiner Entwicklung hin zur Dokumentation 

- **Es wurde festgelegt** nach beidseitigem Einverständnis, das Herr Ziegert Herr Marthaus in der Dokumentierung seiner Bilderkennungssoftware unterstützt

-> **Neue Rolle: Dokumentierung Bilderkennungssoftware** für Herr Marthaus

- **Es wurde festgelegt** nach beidseitige Einverständnis, das Herr Kurth Frau Schubert bei Ihrer Bilderkennungssoftware unterstützt -> Teil dieses Vorhabens sind bereits Frau Schubert selbst und Herr Miersch

-> **Neue Rolle: Dokumentierung Bilderkennungssoftware** für Frau Schubert


- Weiterhin wurde über fehlende Akkus für den Fahrroboter besprochen und das dies die Code-Testung weiter hinter verschiebt


**Bitte auch unbedingt hier unter diesem Punkt die Zielstellung anpassen**

==== Zielstellung zur 2. Iteration
Unsere **Zielstellung für die 2. Iteration** vom Zeitraum 20.11.2023 - 04.12.2023 haben wir folgende Punkte in unser Augenmerk genommen:

- 1. Wir wollen alle Roboterfunktionen im Sinne der Ansprechbarkeit der einzelnen Glieder ansprechen und ROS II implementieren -> wie o. g. übernimmt Frau Claire Schubert beide genannten Ziele.

- 2. Wir wollen eine Bilderkennungsdemo mittels Open CV kreieren und demnach erst einmal aufgrund der Schwierigkeiten des Akkus, erst einmal ein Videoähnlichen Feed hierfür nutzen. Dies übernimmt das Entwicklungsteam II.

- 3. Wir haben als Team geklärt, dass eine Anwesenheitspflicht zur Beginn einer Iteration besteht, um eine allgemeine Standerfassung durchführen zu können und unseren Pläne bzw. Ziele zu besprechen.

- 4. Wir planen den Akku von Herr Prof. Neugebauer etwa zum 23.11.2023 (Donnerstag) zu erhalten. Ansonsten ist dies weiterhin mit Verzögerungen verbunden. 


==== Ausblick
Unser Ausblick bis zum Ende der 2. Iteration und mit Beginn der 3. Iteration als Team ist die Zusammenführung der Bilderkennungssoftware und die Garantie der Funktionalität des Fahrroboters ins seiner Gesamtheit. 
[WEITERS FOLGT !!!] 