= Dokumentation: Follow-Me-Fahrroboter
 Modulleiter: Herr Prof. Dr. -Ing. Habil. Jürgen Anke; Auftraggeber: Herr. Prof. Dr. -Ing. Mario Neugebauer; Projekt-Coach: Herr Christoph Zirkelbach;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]

== Allgemein
Dieses Projekt stellt eine Teamarbeit mit Beginn im 3. Semester im Umfang von acht Personen im Modul Software Engineering I und im weiterführenden Modul im 4. Semester Software Engineering II dar. Modulleitung übernimmt niemand geringeres als Herr Prof. Dr.-Ing. Habil. Jürgen Anke; Auftraggeber stellt Herr Prof. Dr.-Ing. Mario Neugebauer dar und unser Projekt-Coach ist Herr Christoph Zirkelbach. 

=== Fristen
**Abgabe Belegarbeit: 26.01.2024**

=== Auftraggeber
Für unser gegebenes Projekt "Follow-Me Fahrroboter" stellt sich Herr Prof. Dr. -Ing. Mario Neugebauer als Auftraggeber bzw. als Product Owner und dient demnach als Hauptansprechpartner.

=== Rollenverteilung
Die Aufgaben wurden hauptsächlich nach Interessen- und Expertisengebieten verteilt und sollen im allgemeinen zum Anreiz dienen gestellte bzw. übernommene Aufgaben auch vollständig und nach bestem Wissen und Gewissen abzuschließen. [WIRD NOCH ERGÄNZT]

=== Ablauf der Kommunikation unter Verwendung von Tools
Wir haben uns als Team darauf verständigt unsere interne Kommunikation in dem von unserem Projektleiter Herr Özer erstellten WhatsApp-Gruppe abzuhalten und diesen auch zum allgemeinen Austausch bei Fragen, Problem und Lösungen zu nutzen. Discord dient hier im gleichen Rahmen. In GitHub überwachen wir unsere gegenseitig gestellten Aufgaben und kontrollieren Projektstruktur. 

=== Teammitglieder
|===
| Teammitglied | Tätigkeitsbeschreibung 
|**Taylan Özer, Wirtschaftsinformatik, s85500**| Herr Özer übernimmt die **Projektleitung** und demnach auch administrative Aufgaben. Aufgabenfeld und Tätigkeit sind dynamisch und mit den anderen Projektrollen fließend.

|**Claire Schubert, Wirtschaftsinformatik, s85609** | Frau Schubert übernimmt zu Ihrer Tätigkeit als **stellvertretende Projektleitung** ebenfalls die Rolle als **Creative Lead** und **Architect**. Sie teilt des Weiteren Aufgaben den anderen Teammitgliedern zu und dient als Ansprechperson im technischen Zusammenhang mit dem Fahrroboter. 

|**Theresa Stasch, Wirtschaftsingenieurwesen**| Frau Stasch übernimmt zunächst die Aufgabe zur Pflegung des Beleges und im allgemeinen zur Weiterführung der Dokumentation.[NOCH UNVOLLSTÄNDIG] 

|**Johann Marthaus, Wirtschaftsinformatik, s85567**| Herr Marthaus übernimmt die Rolle als **Lead Developer** und organisiert sich mit **Jonathan Palermo**, **Danny Miersch** und [NAMEN ERGÄNZEN] zum Aufbau der Bilderkennung für den Fahrroboter.

|**Jonathan Palermo, Wirtschaftsinformatik, s85287** | Herr Palermo trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei und insbesondere in der Bilderkennung.

|**Danny Miersch, Wirtschaftsinformatik, s85567** | Herr Miersch trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei. Herr Miersch übernimmt so auch, weitere Nebentätigkeiten, wie mit unter die Kontrolle des Glossars.

|**Jeremy Ziegert, Wirtschaftsinformatik, s85299** | Herr Ziegert trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei.

| **Luca Kurth, Verwaltungsinformatik, s85459** | Herr Kurth trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei.
|===


**ALLE TÄTIGKEITEN WERDE NOCH GENAUER UND BESSER BESCHRIEBEN ES KANN NICHT ALSO NOCH WANDLEN - Taylan**


=== Teamstruktur zur 3. Iteration (05.12.2023 - 19.12.2023)

|===
|Team |Teambeschreibung |Teammitglieder
|**Entwicklungs Team I**
|Entwicklungsteam I unter Leitung von Herr Marthaus ist zu Beginn der 1. Iteration (06.11.2023 - 19.11.2023) für die Bilderkennung des Fahrroboters zuständig.
|Johann Marthaus (Gruppenleitung), Luca Kurth, Jonathan Palermo, Jeremy Ziegert

|**Entwicklungs Team II**
|Entwicklungsteam II stellt die Recherche und die Dokumentation zum Roboter Betriebssystem II (ROS II) sicher und überwacht demnach die Schritte zur Implementierung des Betriebssystems.
|Claire Schubert, Danny Miersch
|===

Die Teammitglieder, welche nicht Teil des genanten Entwicklungsteams I und II sind, führen Ihre oben beschriebenen Aufgaben autonom weiterhin fort.

 - Unsere Teamstruktur blieb analog zur 1. Iteration unverändert und so führen wir diese Teamstruktur zunächst auch in der 2. Iteration fort.

== Iterationen
=== 3. Iteration 05.12.2023 - 19.12.2023 
=== Allgemein
==== Standerfassung aus 2. Iteration

Mit Beginn unserer 3. Iteration mit dem Zeitraum vom 04.12.2023 - 19.12.2023 hielten wir zeitnah am 05.12.2023 (Dienstag) ein Gruppenmeeting zur Erfassung des aktuellen Projektstandes und für das weitere Vorgehen ab. Bei diesem Meeting war ebenfalls Herr Zirkelbach als Projekt-Coach anwesend. 

 - **Erster Punkt:** Unsere Gruppe hatte einige Fragen zur Dokumentation der Architektur. Herr Zirkelbach teilte uns mit, dass in der Dokumentation nur grobe Informationen enthalten sein müssen. Beispielsweise enthält das Notebook Informationen darüber, worum es geht und welche Technik verwendet wird. Hierbei sollten ebenfalls alle Entscheidungen mit ihren dazugehörigen Begründungen und Erkenntnissen berücksichtigt werden. 

 - **Zweiter Punkt:** Ebensfalls kamen Fragen bezüglich des Essence Navigator auf. Hierbei stellte sich heraus, dass der Essence Navigator uns dabei im Rahmen des Lehrprojektes unterstützen soll, herauszufinden in welchem Projektstand wir uns befinden. Grundlegend kann man davon ausgehen, dass es von Vorteil ist, in jeder Interation auf den Essence Navigator zurückzugreifen. Jedoch wurde durch Herr Zirkelbach mitgeteilt, dass die entstandenen Diagramme vom Essence Navigator lediglich in den Iteration Plan für zwwei vollständige Iterationen eingebunden und abgebildet werden sollen.

 - **Dritter Punkt:** Unsere letzte Frage betraf das Development. Den Design-Teil priorisieren wir eher in Software Engineering II - es können jedoch bereits erste Grundgedanken hinzugefügt werden. Des Weiteren können schon erste Entwürfe erstellt werden, für die Kommunikation mit der Hardware. So auch soll das OS ROS II so erklärt werden, dass sogar ein dritter nur anhand dieser nicht all zu komplexen Orientierung sich in die Gruppe mit einfinden könnte.  

 - **Vierter Punkt:** Zuletzt wurden noch grundsätzliche Ziele besprochen. Herr Zirkelbach wird noch einmal im Januar (zur letzten Iteration) mit eingebunden werden. Ebenfalls ist es wichtig die USE-CASEs richtig zu definieren und dementsprechend ein USE-CASE-Diagramm zu erstellen. Ein Beispiel hierfür ist das Starten des Fahrroboters -> das System wird hochgefahren und der Roboter fährt einer Person hinterher. Abschließend muss noch geklärt werden: Ob der Roboter, wenn sich die Person umdreht, ihr folgen soll oder ob er rückwärtsfährt, wenn eine Person sich auf ihn hinzu bewegt. Nebenbei sollte dokumentiert werden welche zusätzlichen Änderungen vorgenommen wurden.

==== Probleme und weitere Belange
- **Erster Punkt:** Es wurde bereits ein USE-CASES-Diagramm von Herr Kurth erstellt, jedoch wurde dieses vor dem Treffen mit dem Projekt-Coach am 05.12.2023 (Dienstag) nicht auf GitHub gepushed. Dieses Diagramm konnte dementsprechend auch nicht Herr Zirkelbach gezeigt werden - nachträglich wurde das Diagramm an Herr Zirkelbach per Email gesendet. 

- **Zweiter Punkt:** Bis zum Sonntag den 10.12.2023 sollte der erste Prototyp funktionieren. Hierbei sollte der Roboter in einem leeren Raum es schaffen einer Person u folgen. 

- **Dritter Punkt:** Wir berieten uns im allgemeinen darüber, ob wir Herr Zirkelbach zeitnah über unsere Ordnerstruktur ansprechen sollten, zwecks der Einführung einer ReadMe-Datei und eines Installation-Guides (Deutsch/Englisch).

- **Vierter Punkt:** Ein Prototyp ist noch nicht vollständig vorhanden -> Software-Komponente fehlt (Herr Marthaus)

- **Fünfter Punkt:** Der Alphabot II lässt sich über seine Kamera und einzelnen Glieder ansprechen

=== Gruppenmeeting 12.12.2023
==== Anlass
Der Anlass für dieses Gruppenmeeting bestand darin, einen allgemeinen Überblick über unsere Belegstruktur zu erhalten und notwendige Dokumentationen.  

**Anwesenheitsliste:**

- Herr Özer (Projektleiter),
- Herr Miersch (Entwickler),
- Herr Ziegert (Dokum. Bilderkennung/Entwicklung),
- Frau Stasch (Entwicklerin)

**Verlauf:**

 - In Klärung mit den anwesenden Teammitgliedern wurde erfragt, ob Frau Schubert ihre Architektur-Konzeption der Bilderkennungssoftware in Stichpunkten darlegen kann, um diesen später als Guide niederschreiben zu können. 

 - Wir diskutierten über das OpenUP und die Relevanz für uns, zwecks Developer Diary

**Es wurde festgelegt* das Frau Schubert, wie o. g. ihre Architektur-Konzeption der Bilderkennungssoftware in Stichpunkten niederschreibt zur späteren Weiterbearbeitung

- Wir beschlossen, dass wir zwecks Belegstruktur uns mehr in das OpenUP reinzulesen

- Herr Özer wird Frau Schubert mitteilen das erst genanntes umgesetzt werden soll

=== Gruppenmeeting 14.12.2023
==== Anlass 
Der Anlass für dieses Gruppenmeeting bestand darin unser allgemeines Vorgehen für unser kommendes Auftraggebergespräch am 15.12.2023 zu besprechen und unser weiteres Vorgehen zu planen. 

**Anwesenheitsliste:**

- Herr Özer (Projektleiter)
- Frau Schubert (Entwicklerin)
- Herr Marthaus (Entwickler)

**Verlauf:**
 - Herr Özer wird mit Herr Miersch das Design.adoc Dokument mit Informationen befüllen, welche Frau Schubert ihm vorher schon zugesendet hat

 - Analog gilt dies auch für das Architecture Notebook mit Herr Miersch und Herr Özer 

 - Es wurde erkannt, das die Kamera ungeeignet ist für unser laufendes Projekt und so sollte diese im Weiteren Verlauf ausgetauscht werden, jedoch muss erst dies in Absprache mit dem Auftraggeber erfolgen


**Es wurde festgelegt*

- Zum 15.12. wird die Thematik einer neuen Kamera angesprochen

- Unser bisheriger Projektstand ergibt sogar schon einen funktionalen und ansprechbaren Prototypen 

- Einarbeitung von Notizen durch Herr Miersch und Herr Özer in das Architecture Notebook


==== Zielstellung zur 3. Iteration
Unsere **Zielstellung für die 3. Iteration** vom Zeitraum 04.12.2023 - 19.12.2023 haben wir folgende Punkte in unser Augenmerk genommen:

- 1. Auftraggebergespräch zum 15.12.2023 (Freitag) um 10:30 Uhr -> Mitteilung des Projektstandes

- 2. Vollständigkeit des 1. Prototypen

- 3. Einarbeitung von Mitschriften in das Architecture Notebook

- 4. 


==== Ausblick
Unser Ausblick bis zum Ende der 3. Iteration und mit Beginn der 4. Iteration als Team ist die Konstruktion eines 1. vollständigen Prototypen. 

[WEITERS FOLGT !!!] 
