=== Gruppenmeeting 14.03.2024 (6. Iteration)
==== Anlass
Der Anlass für dieses Gruppenmeeting vom 14.03.2024 (Donnerstag) bestand darin, die allgemeine Teamkonstellation, die Gruppen - und Arbeitsaufteilung und die Herangehensweise an unsere noch bestehenden Aufgaben (s. u.) zu besprechen.

**Anwesenheitsliste:**

 - Taylan Özer (Projektleiter),
 - Claire Schubert (Entwicklerin),
 - Johann Marthaus (Entwickler),
 - Jeremy Ziegert (Entwickler),
 - Luca Kurth (Entwickler),
 - Danny Miersch (Entwickler)

Abwesenheit (begründet):

  - Herr Palermo (Entwickler)
  

**Verlauf:**

*Die Aufgabenstellungen für die jeweils u. g. Teammitglieder haben sich nun wie folgt geändert:*

        - Bilderkennung: Frau Schubert, Herr Palermo, Herr Marthaus,
        - Alphabot II: Frau Schubert,
        - Qualitätskontrolle über Code: Frau Schubert, Herr Marthaus 


Im Weiteren Verlauf des Gruppenmeetings ergaben sich folgende TO DOs:

- Programmteile von ROS I in ROS II übersetzen -> Wer? (Frau Schubert steht für Fragen offen),
- Test Cases erstellen -> (Guidelines nötig) - Wer?,
- Simulationsumgebung erstellen (Ist es die Zeitwert bzw. lohnt sich hier der Aufwand oder nicht) - Wer?,  
- Bessere Debug Tools (Frau Schubert fragen bei Fragen),
- Bilderkennung verbessern,
- Package aufteilen [...] (GitHub Project Task),
- neue Kamera installieren,
- konkrete und akkurate Dokumentierung,
- regelmäßige Meetings und mehr Austausch,
- nächstes Meeting klären

Sämtliche Tasks sind auch im GitHub-Repository zu finden.

-> Wichtigsten Tasks: Update von ROS I zu ROS II und die Bilderkennung verbessern - Wer?

Identifizierte Probleme:

 - Bilderkennung zuverlässig? Auswertung? Qualität?,
 - Batterielaufzeit (Läuft 30 Min und lädt 1h)


*Lösung:*

 - Herr Miersch:

Herr Miersch will die Dokumentation übernehmen, einen Teil der Codearbeit von Herr Marthaus abnehmen, zusätzlich will er Rücksprache mit den anderen auch u. a. dem Projekt-Coach halten, Test-Cases schreiben und sich genauer einlesen in die Anforderungen für das Modul SE II.

- Herr Kurth:

Herr Kurth übernimmt die Übersetzung von ROS I zu ROS II F(Frau Schubert steht bei Fragen zur Seite) und dokumentiert seine Arbeitsschritte ausführlich.

- Frau Schubert:

Frau Schubert übernimmt die Kamerastream Überarbeitung.

- Herr Ziegert:

Herr Ziegert übernimmt die Erstellung der Simulationsumgebung (URL-Links hat Frau Schubert zur Unterstützung schon bereits auf GitHub im Repository bereitgestellt). Hinzukommt das er diese Ergebnisse der Gruppe auch noch erklären bzw. einmal präsentieren soll und so gleich auf die Machbarkeit für uns hinrecherchiert.

- Herr Özer:

Herr Özer übernimmt die Qualitätskontrolle für das Projekt und nimmt sämtliche Arbeiten im Team auch ab.

(Sofern hier nicht namentlich aufgeführt, dann bereits o. g.)

*Weiteres:*

Frau Schubert gab den Hinweis, dass jeder sich in seine gestellten Aufgaben einmal hineinliest und diese demnach für sich am Wochenende (15.03. - 17.03.) persönlich einmal evaluiert und Zeit und Aufwand abwägt und bis zum Montag (18.03.) ein Feedback darüber abgibt, wie lange er bzw. sie für diese Aufgabe voraussichtlich benötigen wird.

==== Zielstellung zur 6. Iteration
Unsere **Zielstellung für die 6. Iteration** vom Zeitraum 11.03.2024 - 25.03.2024 haben wir folgende Punkte in unser Augenmerk genommen:

-> Erst nach weiterer Absprache.

*Teamentschluss zu o. g. Aufgaben:*

- Herr Kurth wird für die o. g. Aufgaben zwei Wochen, mit Stand vom 18.03.2024 (Montag) - 01.04.2024 (Montag) benötigen. 

- Herr Miersch wird für die o. g. Aufgaben zwei Wochen, mit Stand vom 18.03.2024 (Montag) - 01.04.2024 (Montag) benötigen. 

- Herr Palermo wird für die o. g. Aufgaben drei Wochen, mit Stand vom 18.03.2024 (Montag) - 08.04.2024 (Montag) benötigen (nach extra Onlineeinweisung).

- Herr Marthau wird für die o. g. Aufgaben zwei Wochen, mit Stand vom 18.03.2024 (Montag) - 01.04.2024 (Montag) benötigen. Er wird in der ersten Woche bereits mit der YOLO-Bilderkennung beginnen wollen.

- Frau Schubert wird für die o. g. Aufgaben drei Wochen, mit Stand vom 18.03.2024 (Montag) - 01.04.2024 (Montag) benötigen.

- Herr Özer wird für die o. g. Aufgaben zwei Wochen, mit Stand vom 18.03.2024 (Montag) - 01.04.2024 (Montag) benötigen. 

- Herr Ziegert wird für die o. g. Aufgaben zwei Wochen, mit Stand vom 18.03.2024 (Montag) - 01.04.2024 (Montag) benötigen. 


=== Projekt-Coach-Meeting
==== Anlass
Der Anlass für dieses Meeting vom 28.03.2024 (Donnerstag) bestand darin, die allgemeine Bewertung unseres Beleges durch Herr Zirkelbach als Projektcoach entgegenzunehmen. Und so auch für uns die daraus resultierenden Verbesserungen auch umzusetzen.

**Anwesenheitsliste:**

 - Herr Zirkelbach (Projekt-Coach),
 - Taylan Özer (Projektleiter),
 - Claire Schubert (Entwicklerin),
 - Johann Marthaus (Entwickler),
 - Jeremy Ziegert (Entwickler),
 
**Verlauf:**

1. 
Projektmanagement 

- Tätigkeitsfelder sind nicht ganz klar. 

2. 
"Lessons learned"
ist zu knapp.

3. 
Aufgabenbereich nur „Dokumentation“ entfernen aus dem Beleg. 

4. 
„Beleg pflege“ herausnehmen, eher als interne Information gedacht, als wirkliche relevanz für das Modul.

5. 
Test verantwortlicher wurde geklärt.

6.  
Risiken erfassen: 
Risiko 2: „GitHub-Push“ ?, allgemeiner beschreiben, 3:, 5 -> Risiken ordentlich benennen

7. 
Iterationspläne fehlerhaft formatiert nach PDF übertrag -> kontrollieren und verbessern

8. 
Developer Diary -> kontrollieren; fehlerhafte Generierung und nochmal erneuern und klarer gliedern je nach Iterationsplan.

9. 
Vision, Glossar, Systemwide Requierements:
Vision: Problemstatement erneuern und klarstellen, allgemeiner formulieren -> Eher Machbarkeitsstudie als ernsthaftes wirtschaftliches Problem.

10.
Stakeholder:  

- Stakeholder Beschreibung fehlerhaft -> erneuern bzw. vervollständigen und Stakeholder DSGVO hinzufügen

11.
Benutzerumgebung überarbeiten: 
- Aktuell noch Informationen enthalten die Teamintern sind und nicht in das Verzeichnis gehören 

12.
Use Cases: Entscheidung treffen ob ein oder mehrere Use Cases 

- Person als Stakeholder erfassen

- Herr Neugebauer kann auch als Stakeholder gesetzt werden 

13. 
Nichtfunktionale Anforderungen: 

- keine IDs,

- Testbarkeit zu ungenau, 

- Angabe für Zeiteinheiten, 

- wenn noch keine genauen Angaben: „Wird erst während Machbarkeitsstudie definiert“,

- allgemein zu ungenau, 

- Auftraggeber als Stakeholder 

14. 
Glossar, Domainmodell: 

- Abb. 2: (Name ändern zu: Domainmodell) wirklich alle Datenstrukturen ?

- Tabellenbezeichnung fehlt 

- Abb. 3: ausführlicher 

15.
Architecture Notebook:
- wie wirken sich funktionelle und nichtfunktionale Anforderungen auf die Struktur aus ?
- wenn etwas eingesetzt wird -> begründen, 
- Architekturmechanismen zum Teil falsch verstanden (nicht was genutzt wird) dazu Folie zu Architekturmechanismen von Herr Prof. Anke 

16.
Dokumention der Architektur in verschiedenen Schichten (Beschreiben)

- z.B. ROS -> Packages -> Eigenentwicklung/Import 

17.

- Tests weiter bearbeiten