= Dokumentation: Follow-Me-Fahrroboter
Luca Kurth <s85459@htw-dresden.de>; Jonathan Palermo <s85287@htw-dresden.de>; Jeremy Ziegert <s85299@htw-dresden.de>; Taylan Özer <s85500@htw-dresden.de>; Danny Miersch <s85567@htw-dresden.de>; Johann Marthaus <s85892@htw-dresden.de>; Theresa Stasch <s82413@htw-dresden.de>; Tobias Schubert <s85609@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute
== Iteration 

In der ersten Iteration, die vom 06.11 bis zum 19.11.2023 stattfand, kam es zum ersten Treffen mit dem Auftraggeber ( Herr Neugebauer). Dabei wurden wesentliche Informationen über das bevorstehende Projekt ausgetauscht. Während des Treffens erhielt unsere Gruppe, den für den Follow-Me-Fahrroboter benötigten, Bausatz. Der Auftraggeber schlug vor bei der Erstellung der Software mit dem Roboterbetriebssystem ROS 2 zu arbeiten. Hierbei benötigt es jedoch weiterer Klärung in der Gruppe, ob das Arbeiten mit diesem System mit zu viel Aufwand verbunden ist. Jedes Team Mitglied setzt sich mit ROS 2 auseinander, daraufhin wird in der Gruppe gemeinschaftlch über die Verwendung des Systems entschieden. Von hoher Bedeutung für unser Projekt ist die Bilderkennung. Der Auftraggeber emphiel die Arbeit mit Open CV. Da jedoch in unsere Gruppe bereits eine Idee für die Bilderkennung vorlag, teilten wir dem Auftraggeber diese mit. Das Prinzip berut dabei auf der Bestimmung eines Winkels.  Grundsätzlich besteht die Kamera Steurung aus zwei Servo Motoren bei denen jeweils ein Winkel eingestellt werden kann. Der Winkel wird bestimmt, indem ein Bild Analyse Programm ermittel was und wo sich im Bild befindet. Auf dieser Basis können die X und Y Koordinaten ausgemacht werden. Mit der X Koordinate und dem Kamera Winkel wird hierbei bestimmt in welchem Winkel sich die Person zum Roboter befindet.Mit disem Winkel X und dem Winkel Y, der sich genau wie der Winkel X aus diesem Verfahren zusammensetzt, können nun die Servo Motoren so angepasst werden, dass die Person sich in der Mitte des Bildes befindet. Mittels des Winkels des zweiten Servo Motors und des durch den Abstands Sensor gemessene Länge, kann der Abstand ermittelt werden. Mithilfe dieses Abstandes und dem zuvor ermittelten Winkel des Servo Motors werden die Motoren zunächst so bewegt, dass das Fahrgestell in die gleiche Richtung wie die Kamera zeigt. Anschließend wird ermittelt wie groß der Abstand zur Person ist. Sollte dieser Wert Größer sein als ein vorher definierter Wert sein, bewegt sich der Roboter nach vorne. Der Auftraggeber war gegnüber dieser Idee offen, jedoch ist das exakte bestimmen eine Winkels eher komplizierter. Eine einfachere Variante wäre auf den Winkel zu verzichten und bei der Bilderkennung mit langsamen Drehen und Beobachten der Kamera zu arbeiten. Sollte sich die Person im mittleren Bereich der Kamera befinden, bewegt sich der Roboter gerade aus weiter. Einen weiteren wichtigen Punkt stellt die Benutzeroberfläche des Roboters dar. Hierbei setzt sich unsere Gruppe damit auseinander wie der Roboter starten soll. Hierbei sollte beachten werden, dass der Start des Roboters nicht gleich der Start der Software ist. Es gebe beispielsweise die Möglichkeiten einen Startknopf einzurichten oder der Roboter per Handzeichen zu starten. Jedoch ist die Einrichtung des Starts per Handzeichen wesentlich komplexer.  Der Roboter steht zunächst einmal, jedoch scheint der Akku nicht mit enthalten gewesen zu sein aus der Packung die wir von Hr. Neugebauer erhalten haben. Die mitgelieferte Kamera scheint auch eher fragil befestigt gewesen zu sein. Hr. Neugebauer wurde durch mich informiert das wir keine Akkus mitgeliefert bekommen haben und das wir dann nochmal eine Mail an ihn in aller Gesamtheit nach schreiben. Demnach verschiebt sich die Installation der Raspi-Software etwas weiter zeitlich nach hinten und die allgemeine Testung der Funktionalitäten. ROS 2 ist ja auch noch zu berücksichtigen als OS. 

=== Retrospektive der Teammitglieder
[%header]
|===
| Teammitglied | Pro  | Contra
|Luca Kurth|xx|xx
|Jonathan Palermo|xx|xx
|Jeremy Ziegert|xx|xx
|Taylan Özer|xx|xx
|Johann Marthaus|xx|xx
|Danny Miersch|xx|xx
|Theresa Stasch|xx|xx
|===
=== Retrospektive des gesamten Teams 
[%header]
|===
| Pro  | Contra
|===
=== Komplexitätspunkte pro Iteration