= Dokumentation: Follow-Me-Fahrroboter
 Modulleiter: Herr Prof. Dr. -Ing. Habil. Jürgen Anke; Auftraggeber: Herr. Prof. Dr. -Ing. Mario Neugebauer; Projekt-Coach: Herr Christoph Zirkelbach;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute
== Allgemein
Dieses Projekt stellt eine Teamarbeit mit Beginn im 3. Semester im Umfang von acht Personen im Modul Software Engineering I und im weiterführenden Modul im 4. Semester Software Engineering II dar. Modulleitung übernimmt niemand geringeres als Herr Prof. Dr.-Ing. Habil. Jürgen Anke; Auftraggeber stellt Herr Prof. Dr.-Ing. Mario Neugebauer dar und unser Projekt-Coach ist Herr Christoph Zirkelbach. 

=== Fristen
**Abgabe Belegarbeit: 26.01.2024**
WEITERE FRISTEN FOLGEN

=== Auftraggeber
Für unser gegebenes Projekt "Follow-Me Fahrroboter" stellt sich Herr Prof. Dr. -Ing. Mario Neugebauer als Auftraggeber bzw. als Product Owner und dient demnach als Hauptansprechpartner.

=== Teammitglieder
|===
| Teammitglied | Tätigkeitsbeschreibung 
|**Taylan Özer** | Herr Özer übernimmt die **Projektleitung** und demnach auch administrative Aufgaben. Aufgabenfeld und Tätigkeit sind dynamisch und mit den anderen Projektrollen fließend.

|**Claire Schuster** | Frau Schuster übernimmt zu Ihrer Tätigkeit als **stellvertretende Projektleitung** ebenfalls die Rolle als **Creative Lead** und **Architect**. Sie teilt des Weiteren Aufgaben den anderen Teammitgliedern zu und dient als Ansprechperson im technischen Zusammenhang mit dem Fahrroboter. 

|**Theresa Stasch**| Frau Stasch übernimmt zunächst die Aufgabe zur Pflegung des Beleges und im allgemeinen zur Weiterführung der Dokumentation.[NOCH UNVOLLSTÄNDIG] 

|**Johann Marthaus**| Herr Marthaus übernimmt die Rolle als **Lead Developer** und organisiert sich mit **Jonathan Palermo**, **Danny Miersch** und [NAMEN ERGÄNZEN] zum Aufbau der Bilderkennung für den Fahrroboter.

|**Jonathan Palermo** | Herr Palermo trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei und insbesondere in der Bilderkennung.

|**Danny Miersch** | Herr Miersch trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei. Herr Miersch übernimmt so auch, weitere Nebentätigkeiten, wie mit unter die Kontrolle des Glossars.

|**Jeremy Ziegert** | Herr Ziegert trägt die Rolle als **Entwickler** und trägt mit zur Entwicklung des Fahrroboters bei.

| **Luca Kurth** | Herr Kurth trägt die Rolle des **Entwicklers** und trägt mit zur Entwicklung des Fahrroboters bei.

|===

**ALLE TÄTIGKEITEN WERDE NOCH GENAUER UND BESSER BESCHRIEBEN ES KANN NICHT ALSO NOCH WANDLEN - Taylan**

== Iterationen
=== 1. Iteration 06.11.2023 - 19.11.2023 
=== Allgemein
Die Hürde mit Herausgabe aller Projekte und Ihrer Projektleiter am 30.10.2023 bestand darin, zunächst das Team in seiner Gesamtheit erst einmal zusammenzutragen.

**Projektleiter (Taylan Özer):**
So schrieb ich zunächst erst einmal jene Beteiligten für unser Projekt an und wartete circa eine Woche auf eine Rückmeldung aller aus unserem Team - jeder hat sich bei mir zurückgemeldet. Im Anschluss entstand eine WhatsApp-Gruppe, ein GitHub-Repository (geforked von Herr Prof. Anke und Herr Zirkelbach) und ein Discord-Server - unsere interne Kommunikation stand. Ich kümmerte mich demnach auch um unser erstes Auftraggeber-Gespräch mit Herr Prof. Neugebauer und etwa zwei Tage später um ein Projekt-Coach Gespräch.

**Schwierigkeiten Projektleiter**
Bestandteil dieser Iteration war auch ein Projekt-Coach Gespräch und diesem kamen wir auch zeitnah nach. Herr Zirkelbach erklärte uns als Team, dass es zunächst wichtig ist Rollen festzulegen und nicht all zu steif auf ein Konzept zu beharren, nicht bevor wir das erste Auftraggebergespräch geführt hätten. Wir gingen Herr Zirkelbachs Tipps nach und warteten auf das sehnlichst herbeigesehnte erste Gespräch mit Herr Prof. Neugebauer als unser Auftraggeber. 

Zu diesem Zeitpunkt stand für uns als Team erst einmal die Rollenverteilung und die allgemeine Arbeitsstruktur klar und danach orientierten wir uns zunächst.

Erwähntes Auftraggebergespräch fand zunächst erst einmal an zwei der geplanten Zieltage nicht statt, aufgrund dessen das Herr Neugebauer diese aus persönlichen Gründen hat verschieben müssen. 

Am 17.11.2023 konnten wir dann unser geplantes Treffen mit Herr Prof. Neugebauer nachgehen und diese ergaben dann so auch folgende Punkte für uns:

- Klärung Aufbau des Alphabot 2 (Fahrroboter),
- Klärung Betriebssystem -> Raspi OS oder ROS 2?,
- Klärung OpenCV, zwecks Bilderkennung,
- Zielstellung für dieses 3. Semester -> Hr. Prof. Neugebauer stimmte uns wie folgt zu: 

Die Allgemeine Zielstellung für dieses Semester in Absprache mit Herr Prof. Neugebauer für Software Engineering I ist: Der Fahrroboter soll in seiner Gesamtheit mit einem beliebigen OS (Raspi OS oder ROS 2) stehen und wir sollen uns zunächst auch bereits fortführend um die Bilderkennung des Fahrroboters prüfen. 

-------------------------------------------------------


In der ersten Iteration, die vom 06.11 bis zum 19.11.2023 stattfand, kam es zum ersten Treffen mit dem Auftraggeber (Herr Prof. Dr. Ing. Neugebauer). Dabei wurden wesentliche Informationen über das bevorstehende Projekt ausgetauscht. Während des Treffens erhielt unsere Gruppe, den für den Follow-Me-Fahrroboter benötigten, Bausatz. Der Auftraggeber schlug vor bei der Erstellung der Software mit dem Roboterbetriebssystem ROS 2 zu arbeiten. Hierbei benötigt es jedoch weiterer Klärung in der Gruppe, ob das Arbeiten mit diesem System mit zu viel Aufwand verbunden ist. Jedes Team Mitglied setzt sich mit ROS 2 auseinander und dann wird in der Gruppe gemeinschaftlch über die Verwendung des Systems entschieden. Von hoher Bedeutung für unser Projekt ist die Bilderkennung. Der Auftraggeber empfiel die Arbeit mit Open CV. Da jedoch in unsere Gruppe bereits eine Idee für die Bilderkennung vorlag, teilten wir dem Auftraggeber dies mit. Das Prinzip berut dabei auf der Bestimmung eines Winkels. Mit der X Koordinate und dem Kamerawinkel wird nun bestimmt in welchem Winkel sich die Person zum Roboter befindet. Mit diesem X-Winkel und dem Y-Winkel der sich genau wie der X-Winkel aus diesem Verfahren zusammensetzt können nun die Servomotoren so angepasst werden, dass die Person sich in der Mitte des Bildes befindet.  Grundsätzlich besteht die Kamera Steurung aus zwei Servomotoren bei denen jeweils ein Winkel eingestellt werden kann. Der Winkel wird bestimmt, indem ein Bild-Analyseprogramm ermittelt, welche Objekte sich im Bild befinden. Auf dieser Basis können die X - und Y-Koordinaten ausgemacht werden. Der Roboter steht zunächst einmal, jedoch scheint der Akku nicht mit enthalten gewesen zu sein aus der Packung die wir von Hr. Prof. Neugebauer erhalten haben. Die mitgelieferte Kamera scheint auch eher am Kabel fragil befestigt gewesen zu sein. Hr. Prof. Neugebauer wurde durch mich (Taylan Özer) informiert das wir keine Akkus mitgeliefert bekommen haben und das wir dann nochmal eine Mail an ihn in aller Gesamtheit nach schreiben. Demnach verschiebt sich die Installation der Rasberry Pi-Software etwas weiter zeitlich nach hinten und die allgemeine Testung der Funktionalitäten. ROS 2 ist ja auch noch zu berücksichtigen als OS. 


=== 2. Iteration 20.11.2023 - 04.12.2023
--------------------------------------------------------------
Hey Theresa, 

Taylan hier und hier sind meine Anmerkungen: 

Du hast ausführlich geschrieben das ist gut und Du meintest ja auch Du willst das gerne noch einmal überarbeiten und mein Gedanken hierzu waren weiterhin, dass wir das noch sauberer Untergliedern müssen. Ich arbeite auch einige Sachen ein und wir können dazu gerne Morgen einmal sprechen oder als Team.
