= Dokumentation: Follow-Me-Fahrroboter
Luca Kurth <s85459@htw-dresden.de> Jonathan Palermo <s85287@htw-dresden.de>; V Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute
== Iteration 

In der ersten Iteration, die vom 06.11 bis zum 19.11.2023 stattfand, kam es zum ersten Treffen mit dem Auftraggeber ( Herr Neugebauer). Dabei wurden wesentliche Informationen über das bevorstehende Projekt ausgetauscht. Während des Treffens erhielt unsere Gruppe, den für den Follow-Me-Fahrroboter benötigten, Bausatz. Der Auftraggeber schlug vor bei der Erstellung der Software mit dem Roboterbetriebssystem ROS 2 zu arbeiten. Hierbei benötigt es jedoch weiterer Klärung in der Gruppe, ob das Arbeiten mit diesem System mit zu viel Aufwand verbunden ist. Jedes Team Mitglied setzt sich mit ROS 2 auseinander und dann wird in der Gruppe gemeinschaftlch über die Verwendung des Systems entschieden. Von hoher Bedeutung für unser Projekt ist die Bilderkennung. Der Auftraggeber emphiel die Arbeit mit Open CV. Da jedoch in unsere Gruppe bereits eine Idee für die Bilderkennung vorlag, teilten wir dem Auftraggeber diese mit. Das Prinzip berut dabei auf der Bestimmung eines Winkels. Mit der X Koordinate und dem Kamera Winkel wird nun bestimmt in welchem Winkel sich die Person zum Roboter befindet.Mit disem Winkel X und dem Winkel Y der sich genau wie der Winkel X aus diesem Verfahren zusammensetzt können nun die Servo Motoren so angepasst werden, dass die Person sich in der Mitte des Bildes befindet.  Grundsätzlich besteht die Kamera Steurung aus zwei Servo Motoren bei denen jeweils ein Winkel eingestellt werden kann. Der Winkel wird bestimmt, indem ein Bild Analyse Programm ermittel was und wo sich im Bild befindet. Auf dieser Basis können die X und Y Koordinaten ausgemacht werden.  Der Roboter steht zunächst einmal, jedoch scheint der Akku nicht mit enthalten gewesen zu sein aus der Packung die wir von Hr. Neugebauer erhalten haben. Die mitgelieferte Kamera scheint auch eher fragil befestigt gewesen zu sein. Hr. Neugebauer wurde durch mich informiert das wir keine Akkus mitgeliefert bekommen haben und das wir dann nochmal eine Mail an ihn in aller Gesamtheit nach schreiben. Demnach verschiebt sich die Installation der Raspi-Software etwas weiter zeitlich nach hinten und die allgemeine Testung der Funktionalitäten. ROS 2 ist ja auch noch zu berücksichtigen als OS. 
