= System-Wide Requirements: Follow-Me Fahrroboter
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt Follow-Me Fahrroboter spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. 
//[hier ggf. Verweis einfügen]


//== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

- *NFAU-1:* Die Bedienung des Alphabots soll leicht und ohne Vorkenntnisse möglich sein.

- *NFAU-2:* Die genutzte Software soll leicht zu erlernen sein.

- *NFAU-3:* Das System soll als portable Möglichkeit zur Mitführung gestaltet werden.

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

**Verfügbarkeit** +
// Das System muss eine hohe Verfügbarkeit aufweisen, um sicherzustellen, dass es für Benutzer zugänglich ist, wenn es benötigt wird.  Die Verfügbarkeit kann in Prozent gemessen werden (z.B. 99,9% Verfügbarkeit bedeutet, dass das System 99,9% der Zeit verfügbar ist). Überwachung der Systemverfügbarkeit über einen definierten Zeitraum und Identifizierung von Ausfallzeiten.

- *NFAR-1:* Das System sollte möglichst eine Stunde mit vollgeladenem Akku laufen.

- *NFAR-2:* Der Roboter sollte in der Lage sein durch eine handelsübliche Powerbank, sobald dieser an den Zusatzakku angeschlossen wurde, in Betrieb genommen zu werden.

**Wiederherstellbarkeit** +

- *NFAR-3:* Bei einem Fehler soll das System einfach durch error-handling in der Lage sein, sich nicht vollständig zu Beenden, sondern einen Fehler zu werfen und so weiterhin zu laufen.


=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

**Antwortzeit** +  

- *NFAP-1:* Die Antwortzeit der Bilderkennung soll schnell genug sein um Personen folgen zu können. Eine Verarbeitungszeit muss hier bei < 1 Sekunde sein.

**Durschsatz** +

- *NFAP-2:* Der Alphabot 2 muss in der Lage sein, sich mit einer physischen Geschwindigkeit von mindestens 0,03 Metern pro Sekunde über eine glatte Oberfläche zu bewegen.

- *NFAP-3:* Der Alphabot 2 muss i. S. d. Datendurchsatzes in der Lage sein innerhalb von 60 Sekunden eine korrekte Antwort zur Bilderkennung zu liefern.

**Kapazität** +

- *NFAP-4:* Der Alphabot 2 muss in der Lage sein, Bewegungsdaten mit einer Rate von ca. 100-1000 Datenpaketen pro Sekunde zu verarbeiten.

**Zeiten zum Starten oder Beenden** +

- *NFAP-5:* Der Alphabot 2 samt Software muss in der Lage dazu sein innerhalb von 10 Minuten zu starten und innerhalb von 1 Minute sich vollständig sich zu beenden.

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.

**Kompatibilität** +

- *NFAS-1:* Durch die Integration mit dem OS ROS II, muss das System in der Lage mit anderen Systemen kompatibel zu sein.

**Systeminstallation** +

- *NFAS-2:* Die Installation des Systems muss einfach und gut dokumentiert sein. 


== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
//* Ressourcenbegrenzungen
* zu nutzende Komponenten (Alphabot 2 PI)
* Vorgaben für die Programmiersprache (Python)
* zu unterstützende Plattformen / Betriebssysteme (ROS II)
* Physische Begrenzungen für Hardware, auf der das System betrieben werden soll ( Raspberry Pi 4 8GB) 

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* fester Projektzeitraum - Abgabe 28.06.2024
* Zwischenberichte und regelmäßige Iterations-Meilensteine
* Ressourcenverfügbarkeit (Laborräume sofern nötig und digitale Infrastruktur)

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Datenschutz (Personen im Bild, evtl. ohne eigenes ausdrückliches Einverständnis)
