= Vision: Follow-Me Fahrroboter

{localdatetime}

include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Systems Follow-Me zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die  Details, wie das System Follow-Me Fahrroboter diese Bedarfe erfüllt, werden in der Use-Case und Supplementary Specification beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das System Follow-Me Fahrroboter, das von I01_Follow-Me-Team entwickelt wird. Das System wird es Herr Prof. Dr.-Ing. Neugebauer erlauben, den Fahrroboter ihn folgen zu lassen mittels der eigens entwickelten Bilderkennungssoftware durch das o. g. Team, um damit die Hürden des Alltags zu meistern. Die Hauptaufgabe besteht darin, demjenigen zu folgen der den Ton angibt. Dementsprechend ist so das Problem, eines untreuen Gefährten gelöst.

=== Definitionen, Akronyme und Abkürzungen
Siehe <<#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)


== Positionierung

=== Fachliche Motivation
Inmitten der Herausforderungen moderner Hochschullogistik adressiert das Fahrroboterprojekt die ineffizienten Aspekte innerhalb des Campus-Transportsystems. Die zunehmende Komplexität von Lehr- und Forschungseinrichtungen hat ineffiziente Transportabläufe hervorgebracht. Das angestrebte Ziel ist die Integration modernster Technologie zur Steigerung der betriebswirtschaftlichen Effizienz im hochschulischen Umfeld. Durch die Automatisierung von Transportaufgaben sollen nicht nur physische Belastungen gemildert, sondern auch zeitliche Engpässe überwunden werden. Die Implementierung des Fahrroboters wird als entscheidender Schritt betrachtet, um eine nachhaltige Optimierung von Campus-Arbeitsabläufen und eine Reduzierung der operativen Kosten zu erreichen.



=== Problem Statement

[cols="1,3"]

|===
| Das Problem | Herr Prof. Dr.-Ing. Neugebauer besitzt aktuell noch keinen ähnlichen Roboter.
| betrifft | Prof. Dr.-Ing. Neugebauer HTW Dresden
| die Auswirkung davon ist | kein Weggfährte, niemanden der einen begleitet.
| eine erfolgreiche Lösung wäre | die Realisierung des Fahrroboters mittels einer Bilderkennungssoftware auf einem Raspberry-Pi und einem Alphabot 2.
|===

=== Positionierung des Produkts

[cols="1,3"]
|===
| Für | Prof. Dr.-Ing. Neugebauer
| die | einen Fahrroboter benötigt, um einen Begleiter zu haben
| die Lösung ist ein | Fahrroboter, basierend auf einem Alphabot 2 und dem OS ROS II
| Das | Herr Prof. Dr.-Ing. Neugebauer im Leben unterstützt
| Im Gegensatz zu | bisherigen Lösungen haben wir einen Follow-Me-Ansatz gewählt
| Unser Produkt | Fahrroboter begleitet mittels Bilderkennungssoftware sein Ziel an jeden Ort
|===

== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten

| Prof. Dr.-Ing. Neugebauer | Vergab den Auftrag des Follow-Me Fahrroboters und will diesen gerne als Begleiter nutzen
| Legt den Rahmen und die Bedingungen an dieses Projekt fest und überwacht dies auch. Stellte den Fahrroboter Alphabot 2 und den Raspberry-Pi zur Verfügung

|Entwicklungsteam I/II | Streben die Entwicklung der | Legen die Umsetzung und die Möglichkeiten in Verbindung mit Software und Hardware des Fahrrobters zusammen.
Bilderkennungssoftware für den Fahrroboter an

|===

=== Benutzerumgebung

. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
 - 8 Personen; Mit Abschluss 3. Semester - 7 Personen

. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
 - Jede Iteration ist auf 2 Wochen ausgelegt; Arbeitsschritte sind i. d. R. innerhalb einer jeden Woche zu erledigen; Anpassungen können folgen

. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
 - Es gibt keine besonderen Umgebungsbedingungen

. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
    - Es wird Microsoft VS-Code zur allgemeinen Struktur genutzt, GitHub als Versionsverwaltungssoftware und Py-Charm und wie schon genannt Microsoft VS-Code zur Entwicklung.

. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

    - Das OS ROS II ist im Einsatz und muss mit dem Alphabot 2 kombiniert werden.

//Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.


== Produkt-/Lösungsüberblick

=== Bedarfe und Hauptfunktionen

[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features | Geplantes Release

| Bilderkennungssoftware | hoch | Erkennung einer Person | -

|Aufsetzen des OS ROS II | hoch | Das System dient der allgemeinen Struktur für das Projekt| -


|===


== Zusätzliche Produktanforderungen

//Hinweise:

//. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
//. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
//. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
//. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
//. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.


[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| Erkennung des Abstandes zu einer Person im Bild und folgen | hoch | -
|einwandfreie bzw. einfache Nutzung | hoch | -

|===
