:source-highlighter: highlight.js
:toc:
:toc-title: Inhaltsverzeichnis

= Follow-Me-Fahrroboter User Guide

== Ziel des Handbuchs

Dieses Handbuch soll Nutzern helfen, die Software für den Follow-Me-Fahrroboter zu bedienen. Bitte beachten Sie, dass die Interaktionsmöglichkeiten mit dem Roboter begrenzt sind.

== Einführung

Der Follow-Me-Fahrroboter ist ein autonomer Roboter, der entwickelt wurde, um einer Person zu folgen. Hierbei handelt es sich um einen Protoypen einer Machbarkeitsstudie, die Interaktionsmöglichkeiten sind dementsprechend minimal. Diese Anleitung bietet eine kurze Übersicht über die Einrichtung und Nutzung der Software sowie einige Debugging-Kommandos.

== Aufbau und Organisation der Benutzeroberfläche

// Noch einfügen

== Wichtige Aufgaben

=== Verbindung zum WiFi herstellen

==== Raspberry Pi 4B

[source,bash]
----
ssid: Alphabot2

Password: ubuntu1234
----

==== Verbindung mit SSH herstellen

[source,bash]
----
ssh ubuntu@192.168.4.1

Pw: ubuntu1234
----

==== Jetson Nano

[source,bash]
----
ssid: JetsonNano

Pw: jetson1234
----

==== Verbindung mit SSH herstellen

[source,bash]
----
ssh jetson@192.168.5.1

Pw: jetson
----

=== Projekt von der Konsole ausführen

[source,bash]
----
cd ~/ros2_humble/ && source install/setup.bash
cd ~/ros2_ws/ && source install/setup.bash
cd ~/ros2_ws/src/camera_package/launch

ros2 launch follow_me_arduino_launch.py
----

Es gibt verschiedene Launch-Dateien:

* Launch für die Arduino-Version: `follow_me_arduino_launch.py`
* Launch für die Alphabot2-Version: `follow_me_launch.py`
* Test der Arduino-Version: `arduino_test_launch.py`

== Debugging-Kommandos

=== Kamera-Paket neu installieren

[source,bash]
----
cd ~/ros2_ws/src/ && rm -r -f camera_package && git clone https://github.com/cl-ire/camera_package.git
cd ~/ros2_ws && colcon build --packages-select camera_package
----

=== ROS2-Paket für Waveshare Alphabot2 neu installieren

[source,bash]
----
cd ~/ros2_ws/src/ && rm -r -f ros2_for_waveshare_alphabot2 && git clone https://github.com/cl-ire/ros2_for_waveshare_alphabot2.git
cd ~/ros2_ws && colcon build --packages-select ros2_for_waveshare_alphabot2
----

== Selten genutzte Funktionen und FAQ

*Q:* Kann ich den Roboter mit einer anderen Software steuern?

*A:* Derzeit ist der Follow-Me-Fahrroboter nur mit der bereitgestellten Software kompatibel. Anpassungen können jedoch vorgenommen werden, indem Sie die entsprechenden ROS2-Pakete modifizieren.

Für weitere Fragen und Unterstützung, wenden Sie sich bitte an den Systemadministrator.


