=== Gruppenmeeting am 28.11.2023 (2. Iteration)
==== Anlass 
Der Anlass für dieses außerplanmäßge Gruppenmeeting war, dass sich auf Geheiß von einigen Gruppenmitgliedern im Entwicklerteam II Unmut wegen Ihrer jetzigen Tätigkeiten anberaumt hat.

**Anwesenheitsliste:**

- Herr Özer (Projektleiter),
- Herr Marthaus (Leiter Entwicklungsteam II),
- Herr Ziegert (Entwickler),
- Herr Kurth (Entwickler)

**Verlauf:**

- Klärung der Motivation und der arbeitsmäßgen Standerfassung von Herr Ziegert und Herr Kurth
- Herr Ziegert und Herr Kurth sind einverstanden mit der Umgestaltung ihrer Tätigkeiten, von der Programmierung weg bzw. allgemeiner Entwicklung hin zur Beihilfe in der Bilderkennung 

**Es wurde festgelegt* das nach beidseitigem Einverständnis, Herr Ziegert Herr Marthaus anteilig auch in der Dokumentierung seiner Bilderkennungssoftware unterstützt

-> **Neue Rolle: Dokumentierung der Bilderkennungssoftware** für Herr Marthaus

- **Es wurde festgelegt** nach beidseitige Einverständnis, das Herr Kurth Frau Schubert anteilig auch bei Ihrer Bilderkennungssoftware unterstützt -> Teil dieses Vorhabens sind bereits Frau Schubert selbst und Herr Miersch

-> **Neue Rolle: Dokumentierung der Bilderkennungssoftware** für Frau Schubert
