<<<<<<<< HEAD:Documentation/developer_diary/Besprechungsprotokol/Besprechung_14.03.2024.adoc

== Gruppenmeeting 14.03.2024 (6. Iteration)
>>>>>>>> 5ee0542b2da42e133236337033f4638995915fa3:Documentation/developer_diary/Iterations/Iteration_7.adoc

=== Anlass
Der Anlass für dieses Gruppenmeeting vom 14.03.2024 (Donnerstag) bestand darin, die allgemeine Teamkonstellation, die Gruppen - und Arbeitsaufteilung und die Herangehensweise an unsere noch bestehenden Aufgaben (s. u.) zu besprechen.

**Anwesenheitsliste:**

 - Taylan Özer (Projektleiter),
 - Claire Schubert (Entwicklerin),
 - Johann Marthaus (Entwickler),
 - Jeremy Ziegert (Entwickler),
 - Luca Kurth (Entwickler),
 - Danny Miersch (Entwickler)

Abwesenheit (begründet):

  - Herr Palermo (Entwickler)
  

**Verlauf:**

*Die Aufgabenstellungen für die jeweils u. g. Teammitglieder haben sich nun wie folgt geändert:*

        - Bilderkennung: Frau Schubert, Herr Palermo, Herr Marthaus,
        - Alphabot II: Frau Schubert,
        - Qualitätskontrolle über Code: Frau Schubert, Herr Marthaus 


Im Weiteren Verlauf des Gruppenmeetings ergaben sich folgende TO DOs:

- Programmteile von ROS I in ROS II übersetzen -> Wer? (Frau Schubert steht für Fragen offen),
- Test Cases erstellen -> (Guidelines nötig) - Wer?,
- Simulationsumgebung erstellen (Ist es die Zeitwert bzw. lohnt sich hier der Aufwand oder nicht) - Wer?,  
- Bessere Debug Tools (Frau Schubert fragen bei Fragen),
- Bilderkennung verbessern,
- Package aufteilen [...] (GitHub Project Task),
- neue Kamera installieren,
- konkrete und akkurate Dokumentierung,
- regelmäßige Meetings und mehr Austausch,
- nächstes Meeting klären

Sämtliche Tasks sind auch im GitHub-Repository zu finden.

-> Wichtigsten Tasks: Update von ROS I zu ROS II und die Bilderkennung verbessern - Wer?

Identifizierte Probleme:

 - Bilderkennung zuverlässig? Auswertung? Qualität?,
 - Batterielaufzeit (Läuft 30 Min und lädt 1h)


*Lösung:*

 - Herr Miersch:

Herr Miersch will die Dokumentation übernehmen, einen Teil der Codearbeit von Herr Marthaus abnehmen, zusätzlich will er Rücksprache mit den anderen auch u. a. dem Projekt-Coach halten, Test-Cases schreiben und sich genauer einlesen in die Anforderungen für das Modul SE II.

- Herr Kurth:

Herr Kurth übernimmt die Übersetzung von ROS I zu ROS II F(Frau Schubert steht bei Fragen zur Seite) und dokumentiert seine Arbeitsschritte ausführlich.

- Frau Schubert:

Frau Schubert übernimmt die Kamerastream Überarbeitung.

- Herr Ziegert:

Herr Ziegert übernimmt die Erstellung der Simulationsumgebung (URL-Links hat Frau Schubert zur Unterstützung schon bereits auf GitHub im Repository bereitgestellt). Hinzukommt das er diese Ergebnisse der Gruppe auch noch erklären bzw. einmal präsentieren soll und so gleich auf die Machbarkeit für uns hinrecherchiert.

- Herr Özer:

Herr Özer übernimmt die Qualitätskontrolle für das Projekt und nimmt sämtliche Arbeiten im Team auch ab.

(Sofern hier nicht namentlich aufgeführt, dann bereits o. g.)

*Weiteres:*

Frau Schubert gab den Hinweis, dass jeder sich in seine gestellten Aufgaben einmal hineinliest und diese demnach für sich am Wochenende (15.03. - 17.03.) persönlich einmal evaluiert und Zeit und Aufwand abwägt und bis zum Montag (18.03.) ein Feedback darüber abgibt, wie lange er bzw. sie für diese Aufgabe voraussichtlich benötigen wird.

