=== Gruppenmeeting am 28.11.2023 (2. Iteration)
==== Anlass 
Der Anlass für dieses außerplanmäßge Gruppenmeeting war, dass sich auf Geheiß von einigen Gruppenmitgliedern im Entwicklerteam II Unmut wegen Ihrer jetzigen Tätigkeiten anberaumt hat.

**Anwesenheitsliste:**

- Herr Özer (Projektleiter),
- Herr Marthaus (Leiter Entwicklungsteam II),
- Herr Ziegert (Entwickler),
- Herr Kurth (Entwickler)

**Verlauf:**

- Klärung der Motivation und arbeitsmäßgen Standerfassung von Herr Ziegert und Herr Kurth
- Herr Ziegert und Herr Kurth einverstanden mit der Umgestaltung ihrer Tätigkeiten, von Programmierung weg bzw. allgemeiner Entwicklung hin zur Dokumentation 

**Es wurde festgelegt* nach beidseitigem Einverständnis, das Herr Ziegert Herr Marthaus in der Dokumentierung seiner Bilderkennungssoftware unterstützt

-> **Neue Rolle: Dokumentierung Bilderkennungssoftware** für Herr Marthaus

- **Es wurde festgelegt** nach beidseitige Einverständnis, das Herr Kurth Frau Schubert bei Ihrer Bilderkennungssoftware unterstützt -> Teil dieses Vorhabens sind bereits Frau Schubert selbst und Herr Miersch

-> **Neue Rolle: Dokumentierung Bilderkennungssoftware** für Frau Schubert
